// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef UI_DEVICES_H
#define UI_DEVICES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Devices
extern void ui_Devices_screen_init(void);
extern void ui_Devices_screen_destroy(void);
extern lv_obj_t * ui_Devices;
extern lv_obj_t * ui_Back_to_menu_text1;
extern void ui_event_Back_Arrow2(lv_event_t * e);
extern lv_obj_t * ui_Back_Arrow2;
extern void ui_event_Select_Sensor_Dropdown(lv_event_t * e);
extern lv_obj_t * ui_Select_Sensor_Dropdown;
extern lv_obj_t * ui_Select_Sensor_Label;
extern lv_obj_t * ui_Left_Motor_Data;
extern lv_obj_t * ui_Motor_Image;
extern lv_obj_t * ui_Motor_Data;
extern lv_obj_t * ui_Placeholder;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

