// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#include "../include/ui.h"

lv_obj_t * ui_Devices = NULL;
lv_obj_t * ui_Back_to_menu_text1 = NULL;
lv_obj_t * ui_Back_Arrow2 = NULL;
lv_obj_t * ui_Select_Sensor_Dropdown = NULL;
lv_obj_t * ui_Select_Sensor_Label = NULL;
lv_obj_t * ui_Left_Motor_Data = NULL;
lv_obj_t * ui_Motor_Image = NULL;
lv_obj_t * ui_Motor_Data = NULL;
lv_obj_t * ui_Placeholder = NULL;
// event functions
void ui_event_Back_Arrow2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Main_Menu, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Main_Menu_screen_init);
    }
}

void ui_event_Select_Sensor_Dropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_flag_modify(ui_Left_Motor_Data, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// build functions

void ui_Devices_screen_init(void)
{
    ui_Devices = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Devices, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Devices, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Devices, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_to_menu_text1 = lv_label_create(ui_Devices);
    lv_obj_set_width(ui_Back_to_menu_text1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_to_menu_text1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_to_menu_text1, 19);
    lv_obj_set_y(ui_Back_to_menu_text1, 5);
    lv_label_set_text(ui_Back_to_menu_text1, "Back to Menu");
    lv_obj_set_style_text_color(ui_Back_to_menu_text1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back_to_menu_text1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Arrow2 = lv_imagebutton_create(ui_Devices);
    lv_imagebutton_set_src(ui_Back_Arrow2, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_keyboard_arrow_left_30dp_1f1f1f_fill0_wght400_grad0_opsz24_png, NULL);
    lv_obj_set_width(ui_Back_Arrow2, 24);
    lv_obj_set_height(ui_Back_Arrow2, 26);
    lv_obj_set_x(ui_Back_Arrow2, -5);
    lv_obj_set_y(ui_Back_Arrow2, -2);

    ui_Select_Sensor_Dropdown = lv_dropdown_create(ui_Devices);
    lv_dropdown_set_options(ui_Select_Sensor_Dropdown, "-\nLeft Motor");
    lv_dropdown_set_selected_highlight(ui_Select_Sensor_Dropdown, false);
    lv_obj_set_width(ui_Select_Sensor_Dropdown, 150);
    lv_obj_set_height(ui_Select_Sensor_Dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Select_Sensor_Dropdown, 2);
    lv_obj_set_y(ui_Select_Sensor_Dropdown, -22);
    lv_obj_set_align(ui_Select_Sensor_Dropdown, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Select_Sensor_Dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Select_Sensor_Label = lv_label_create(ui_Devices);
    lv_obj_set_width(ui_Select_Sensor_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Select_Sensor_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Select_Sensor_Label, 6);
    lv_obj_set_y(ui_Select_Sensor_Label, -53);
    lv_obj_set_align(ui_Select_Sensor_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Select_Sensor_Label, "Select Sensor:");
    lv_obj_set_style_text_color(ui_Select_Sensor_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Select_Sensor_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Motor_Data = lv_obj_create(ui_Devices);
    lv_obj_remove_style_all(ui_Left_Motor_Data);
    lv_obj_set_width(ui_Left_Motor_Data, 311);
    lv_obj_set_height(ui_Left_Motor_Data, 209);
    lv_obj_set_x(ui_Left_Motor_Data, -7);
    lv_obj_set_y(ui_Left_Motor_Data, 0);
    lv_obj_set_align(ui_Left_Motor_Data, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Left_Motor_Data, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Left_Motor_Data, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Motor_Image = lv_image_create(ui_Left_Motor_Data);
    lv_image_set_src(ui_Motor_Image, &ui_img_1440723307);
    lv_obj_set_width(ui_Motor_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor_Image, 0);
    lv_obj_set_y(ui_Motor_Image, -210);
    lv_obj_set_align(ui_Motor_Image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Motor_Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Motor_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Motor_Image, 50);

    ui_Motor_Data = lv_textarea_create(ui_Left_Motor_Data);
    lv_obj_set_width(ui_Motor_Data, 144);
    lv_obj_set_height(ui_Motor_Data, 122);
    lv_obj_set_x(ui_Motor_Data, 0);
    lv_obj_set_y(ui_Motor_Data, -1);
    lv_obj_set_align(ui_Motor_Data, LV_ALIGN_BOTTOM_LEFT);
    lv_textarea_set_text(ui_Motor_Data, "Revolutions:\nVelocity:\nTorque:\nEncoder Counts:");
    lv_textarea_set_placeholder_text(ui_Motor_Data, "Placeholder...");
    lv_obj_set_style_text_color(ui_Motor_Data, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Motor_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Motor_Data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Motor_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Motor_Data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Motor_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Placeholder = lv_label_create(ui_Left_Motor_Data);
    lv_obj_set_width(ui_Placeholder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Placeholder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Placeholder, -25);
    lv_obj_set_y(ui_Placeholder, 20);
    lv_obj_set_align(ui_Placeholder, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Placeholder, "Graph(s) here");
    lv_obj_set_style_text_color(ui_Placeholder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Placeholder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Back_Arrow2, ui_event_Back_Arrow2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Sensor_Dropdown, ui_event_Select_Sensor_Dropdown, LV_EVENT_ALL, NULL);

}

void ui_Devices_screen_destroy(void)
{
    if(ui_Devices) lv_obj_del(ui_Devices);

    // NULL screen variables
    ui_Devices = NULL;
    ui_Back_to_menu_text1 = NULL;
    ui_Back_Arrow2 = NULL;
    ui_Select_Sensor_Dropdown = NULL;
    ui_Select_Sensor_Label = NULL;
    ui_Left_Motor_Data = NULL;
    ui_Motor_Image = NULL;
    ui_Motor_Data = NULL;
    ui_Placeholder = NULL;

}
