// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#include "../include/ui.h"

lv_obj_t * ui_Main_Menu = NULL;
lv_obj_t * ui_UoA_Logo = NULL;
lv_obj_t * ui_UoA_Engineering = NULL;
lv_obj_t * ui_Options_Panel = NULL;
lv_obj_t * ui_Run_Pgm_Button = NULL;
lv_obj_t * ui_Run_Pgm_Label = NULL;
lv_obj_t * ui_Select_Pgm_Button = NULL;
lv_obj_t * ui_Select_Pgm_Label = NULL;
lv_obj_t * ui_Settings_Button = NULL;
lv_obj_t * ui_Settings_Label = NULL;
lv_obj_t * ui_Devices_Button = NULL;
lv_obj_t * ui_Devices_Label = NULL;
// event funtions
void ui_event_Run_Pgm_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Run_Program, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Run_Program_screen_init);
    }
}

void ui_event_Select_Pgm_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Select_Program, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Select_Program_screen_init);
    }
}

void ui_event_Settings_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Devices_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Devices, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Devices_screen_init);
    }
}

// build funtions

void ui_Main_Menu_screen_init(void)
{
    ui_Main_Menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main_Menu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UoA_Logo = lv_image_create(ui_Main_Menu);
    lv_image_set_src(ui_UoA_Logo, &ui_img_2110221588);
    lv_obj_set_width(ui_UoA_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UoA_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UoA_Logo, -137);
    lv_obj_set_y(ui_UoA_Logo, -15);
    lv_obj_set_align(ui_UoA_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UoA_Logo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_UoA_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_UoA_Logo, 200);

    ui_UoA_Engineering = lv_label_create(ui_Main_Menu);
    lv_obj_set_width(ui_UoA_Engineering, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UoA_Engineering, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UoA_Engineering, -131);
    lv_obj_set_y(ui_UoA_Engineering, 89);
    lv_obj_set_align(ui_UoA_Engineering, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UoA_Engineering, "Engineering");
    lv_obj_set_style_text_color(ui_UoA_Engineering, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UoA_Engineering, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UoA_Engineering, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Options_Panel = lv_obj_create(ui_Main_Menu);
    lv_obj_set_width(ui_Options_Panel, 233);
    lv_obj_set_height(ui_Options_Panel, 226);
    lv_obj_set_x(ui_Options_Panel, 104);
    lv_obj_set_y(ui_Options_Panel, 1);
    lv_obj_set_align(ui_Options_Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Options_Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Options_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Options_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Options_Panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Options_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Run_Pgm_Button = lv_button_create(ui_Options_Panel);
    lv_obj_set_width(ui_Run_Pgm_Button, 228);
    lv_obj_set_height(ui_Run_Pgm_Button, 45);
    lv_obj_set_x(ui_Run_Pgm_Button, 0);
    lv_obj_set_y(ui_Run_Pgm_Button, -83);
    lv_obj_set_align(ui_Run_Pgm_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Run_Pgm_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Run_Pgm_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Run_Pgm_Button, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Run_Pgm_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Run_Pgm_Label = lv_label_create(ui_Run_Pgm_Button);
    lv_obj_set_width(ui_Run_Pgm_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Run_Pgm_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Run_Pgm_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Run_Pgm_Label, "Run Program");

    ui_Select_Pgm_Button = lv_button_create(ui_Options_Panel);
    lv_obj_set_width(ui_Select_Pgm_Button, 228);
    lv_obj_set_height(ui_Select_Pgm_Button, 45);
    lv_obj_set_x(ui_Select_Pgm_Button, 0);
    lv_obj_set_y(ui_Select_Pgm_Button, -29);
    lv_obj_set_align(ui_Select_Pgm_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Select_Pgm_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Select_Pgm_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Select_Pgm_Button, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Select_Pgm_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Select_Pgm_Label = lv_label_create(ui_Select_Pgm_Button);
    lv_obj_set_width(ui_Select_Pgm_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Select_Pgm_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Select_Pgm_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Select_Pgm_Label, "Select Program");

    ui_Settings_Button = lv_button_create(ui_Options_Panel);
    lv_obj_set_width(ui_Settings_Button, 228);
    lv_obj_set_height(ui_Settings_Button, 45);
    lv_obj_set_x(ui_Settings_Button, 0);
    lv_obj_set_y(ui_Settings_Button, 81);
    lv_obj_set_align(ui_Settings_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Settings_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Button, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Label = lv_label_create(ui_Settings_Button);
    lv_obj_set_width(ui_Settings_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Settings_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Label, "Settings");

    ui_Devices_Button = lv_button_create(ui_Options_Panel);
    lv_obj_set_width(ui_Devices_Button, 228);
    lv_obj_set_height(ui_Devices_Button, 45);
    lv_obj_set_x(ui_Devices_Button, 0);
    lv_obj_set_y(ui_Devices_Button, 26);
    lv_obj_set_align(ui_Devices_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Devices_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Devices_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Devices_Button, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Devices_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Devices_Label = lv_label_create(ui_Devices_Button);
    lv_obj_set_width(ui_Devices_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Devices_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Devices_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Devices_Label, "Devices");

    lv_obj_add_event_cb(ui_Run_Pgm_Button, ui_event_Run_Pgm_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select_Pgm_Button, ui_event_Select_Pgm_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_Button, ui_event_Settings_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Devices_Button, ui_event_Devices_Button, LV_EVENT_ALL, NULL);

}

void ui_Main_Menu_screen_destroy(void)
{
    if(ui_Main_Menu) lv_obj_del(ui_Main_Menu);

    // NULL screen variables
    ui_Main_Menu = NULL;
    ui_UoA_Logo = NULL;
    ui_UoA_Engineering = NULL;
    ui_Options_Panel = NULL;
    ui_Run_Pgm_Button = NULL;
    ui_Run_Pgm_Label = NULL;
    ui_Select_Pgm_Button = NULL;
    ui_Select_Pgm_Label = NULL;
    ui_Settings_Button = NULL;
    ui_Settings_Label = NULL;
    ui_Devices_Button = NULL;
    ui_Devices_Label = NULL;

}
