// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef UI_MAIN_MENU_H
#define UI_MAIN_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main_Menu
extern void ui_Main_Menu_screen_init(void);
extern void ui_Main_Menu_screen_destroy(void);
extern lv_obj_t * ui_Main_Menu;
extern lv_obj_t * ui_UoA_Logo;
extern lv_obj_t * ui_UoA_Engineering;
extern lv_obj_t * ui_Options_Panel;
extern void ui_event_Run_Pgm_Button(lv_event_t * e);
extern lv_obj_t * ui_Run_Pgm_Button;
extern lv_obj_t * ui_Run_Pgm_Label;
extern void ui_event_Select_Pgm_Button(lv_event_t * e);
extern lv_obj_t * ui_Select_Pgm_Button;
extern lv_obj_t * ui_Select_Pgm_Label;
extern void ui_event_Settings_Button(lv_event_t * e);
extern lv_obj_t * ui_Settings_Button;
extern lv_obj_t * ui_Settings_Label;
extern void ui_event_Devices_Button(lv_event_t * e);
extern lv_obj_t * ui_Devices_Button;
extern lv_obj_t * ui_Devices_Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

