// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_Chart_Xaxis;
extern lv_obj_t * ui_Chart_Yaxis1;
extern lv_obj_t * ui_Chart_Yaxis2;
extern lv_obj_t * ui_PrintPanel;
extern lv_obj_t * ui_DisplaySwap;
extern lv_obj_t * ui_SwitchFrame;
extern void ui_event_Switch(lv_event_t * e);
extern lv_obj_t * ui_Switch;
extern lv_obj_t * ui_DisplayPrintText;
extern lv_obj_t * ui_DisplayChartText;
extern lv_obj_t * ui_RunningText;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_StopPanel;
extern lv_obj_t * ui_StopText;
extern lv_obj_t * ui_PrintLine1;
extern lv_obj_t * ui_PrintLine2;
extern lv_obj_t * ui_PrintLine3;
extern lv_obj_t * ui_PrintLine4;
extern lv_obj_t * ui_PrintLine5;
extern lv_obj_t * ui_PrintLine6;
extern lv_obj_t * ui_PrintLine7;
extern lv_obj_t * ui_PrintLine8;
extern lv_obj_t * ui_Legend;
extern lv_obj_t * ui_LegendLabel;
extern lv_obj_t * ui_ULegend;
extern lv_obj_t * ui_UColour;
extern lv_obj_t * ui_ULegendText;
extern lv_obj_t * ui_ELegend;
extern lv_obj_t * ui_EColour;
extern lv_obj_t * ui_ELegendText;
extern lv_obj_t * ui_EncLegend;
extern lv_obj_t * ui_EncColour;
extern lv_obj_t * ui_EncLegendText;
extern lv_obj_t * ui_LeftDistLegend;
extern lv_obj_t * ui_LeftDistColour;
extern lv_obj_t * ui_LeftDistLegendText;
extern lv_obj_t * ui_RightDistLegend;
extern lv_obj_t * ui_RightDistColour;
extern lv_obj_t * ui_RightDistLegendText;
extern lv_obj_t * ui_ArmEncLegend;
extern lv_obj_t * ui_ArmEncColour;
extern lv_obj_t * ui_ArmEncLegendText;
extern lv_obj_t * ui_OnScreenStopButton;
extern lv_obj_t * ui_StopButtonText;

// CUSTOM VARIABLES & FUNCTIONS
extern lv_chart_series_t *series_U;
extern lv_chart_series_t *series_E;
extern lv_chart_series_t *series_WheelEnc;
extern lv_chart_series_t *series_ArmEnc;
extern lv_chart_series_t *series_LeftDist;
extern lv_chart_series_t *series_RightDist;
extern void update_y_axis(int min, int max);
extern void lvgl_print(int line_number, char* text, ...);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

