// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#include <string.h>
#include "../include/ui.h"
#include "../include/main.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Chart = NULL;
lv_obj_t * ui_Chart_Xaxis = NULL;
lv_obj_t * ui_Chart_Yaxis1 = NULL;
lv_obj_t * ui_Chart_Yaxis2 = NULL;
lv_obj_t * ui_PrintPanel = NULL;
lv_obj_t * ui_DisplaySwap = NULL;
lv_obj_t * ui_SwitchFrame = NULL;
lv_obj_t * ui_Switch = NULL;
lv_obj_t * ui_DisplayPrintText = NULL;
lv_obj_t * ui_DisplayChartText = NULL;
lv_obj_t * ui_RunningText = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_StopPanel = NULL;
lv_obj_t * ui_StopText = NULL;
lv_obj_t * ui_PrintLine1 = NULL;
lv_obj_t * ui_PrintLine2 = NULL;
lv_obj_t * ui_PrintLine3 = NULL;
lv_obj_t * ui_PrintLine4 = NULL;
lv_obj_t * ui_PrintLine5 = NULL;
lv_obj_t * ui_PrintLine6 = NULL;
lv_obj_t * ui_PrintLine7 = NULL;
lv_obj_t * ui_PrintLine8 = NULL;
lv_obj_t * ui_ULegend = NULL;
lv_obj_t * ui_UColour = NULL;
lv_obj_t * ui_ULegendLabel = NULL;
lv_obj_t * ui_ELegend = NULL;
lv_obj_t * ui_EColour = NULL;
lv_obj_t * ui_ELegendLabel = NULL;
lv_obj_t * ui_EncLegend = NULL;
lv_obj_t * ui_EncColour = NULL;
lv_obj_t * ui_EncLegendLabel = NULL;
lv_obj_t * ui_DistLegend = NULL;
lv_obj_t * ui_DistColour = NULL;
lv_obj_t * ui_DistLegendLabel = NULL;
// CUSTOM VARIABLES
lv_chart_series_t *series_U = NULL;
lv_chart_series_t *series_E = NULL;
lv_chart_series_t *series_Enc = NULL;
lv_chart_series_t *series_Dist = NULL;


// event functions
void ui_event_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PrintPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Chart, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingsScreen_screen_init);
    }
}

// Custom Functions
void ui_create_chart_series(void)
{
    if(series_U == NULL)
        series_U = lv_chart_add_series(ui_Chart, lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);

    if(series_E == NULL)
        series_E = lv_chart_add_series(ui_Chart, lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);

    if(series_Enc == NULL)
        series_Enc = lv_chart_add_series(ui_Chart, lv_color_hex(0x0000FF), LV_CHART_AXIS_PRIMARY_Y);

    if(series_Dist == NULL)
        series_Dist = lv_chart_add_series(ui_Chart, lv_color_hex(0xFFFFFF), LV_CHART_AXIS_PRIMARY_Y);
}

void update_y_axis(int min, int max)
{
    if (max <= min) max = min + 1;

    int divisions = 4;                 // total labeled major ticks - 1
    int major_step = (max - min) / divisions;
    if (major_step < 1) major_step = 1;

    int total_ticks = divisions * 2 + 1;   // because SquareLine uses 2 minor ticks per division

    // LEFT Y axis
    lv_scale_set_range(ui_Chart_Yaxis1, min, max);
    lv_scale_set_total_tick_count(ui_Chart_Yaxis1, total_ticks);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis1, 2);
    lv_scale_set_label_show(ui_Chart_Yaxis1, true);

    // RIGHT Y axis
    lv_scale_set_range(ui_Chart_Yaxis2, min, max);
    lv_scale_set_total_tick_count(ui_Chart_Yaxis2, total_ticks);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis2, 2);
    lv_scale_set_label_show(ui_Chart_Yaxis2, true);
}

void lvgl_print(int line_number, char* text, ...) {
    //Limit string length to 40 characters
    if (strlen(text) > 40) return;
    //Find correct line
    lv_obj_t* line_obj = NULL;
    switch (line_number) {
        case 1: line_obj = ui_PrintLine1; break;
        case 2: line_obj = ui_PrintLine2; break;
        case 3: line_obj = ui_PrintLine3; break;
        case 4: line_obj = ui_PrintLine4; break;
        case 5: line_obj = ui_PrintLine5; break;
        case 6: line_obj = ui_PrintLine6; break;
        case 7: line_obj = ui_PrintLine7; break;
        case 8: line_obj = ui_PrintLine8; break;
        default: return; // Invalid line number
    }
    //Set line text
    if (line_obj != NULL) {
        char buffer[128]; // buffer to hold the formatted string
        va_list args;
        va_start(args, text);
        vsnprintf(buffer, sizeof(buffer), text, args);
        va_end(args);

        lv_label_set_text(line_obj, buffer);
    }
}

// build functions
void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_Chart, 400);
    lv_obj_set_height(ui_Chart, 185);
    lv_obj_set_x(ui_Chart, 40);
    lv_obj_set_y(ui_Chart, 5);
    lv_obj_add_flag(ui_Chart, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart, 50);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_Xaxis = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart,
                                                                  LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart_Xaxis, false);
    ui_Chart_Yaxis1 = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart_Yaxis1, 2, lv_pct(100));
    lv_obj_set_align(ui_Chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart_Yaxis1, -2 - lv_obj_get_style_pad_left(ui_Chart,
                                                                 LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Yaxis1, 3, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart_Yaxis2 = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart,
                                                                  LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Yaxis2, 3, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart_Yaxis2, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis2, 2 >= 1 ? 2 : 1);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart, LV_MAX3(50, 2, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_PrintPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PrintPanel, 440);
    lv_obj_set_height(ui_PrintPanel, 185);
    lv_obj_set_x(ui_PrintPanel, 20);
    lv_obj_set_y(ui_PrintPanel, 5);
    lv_obj_remove_flag(ui_PrintPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrintPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrintPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PrintPanel, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrintPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrintPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PrintPanel, lv_color_hex(0x3C3B3B), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrintPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrintPanel, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_DisplaySwap = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplaySwap, 480);
    lv_obj_set_height(ui_DisplaySwap, 50);
    lv_obj_set_align(ui_DisplaySwap, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_DisplaySwap, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchFrame = lv_obj_create(ui_DisplaySwap);
    lv_obj_set_width(ui_SwitchFrame, 190);
    lv_obj_set_height(ui_SwitchFrame, 40);
    lv_obj_set_align(ui_SwitchFrame, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SwitchFrame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchFrame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchFrame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch = lv_switch_create(ui_DisplaySwap);
    lv_obj_set_width(ui_Switch, 50);
    lv_obj_set_height(ui_Switch, 25);
    lv_obj_set_align(ui_Switch, LV_ALIGN_CENTER);

    ui_DisplayPrintText = lv_label_create(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplayPrintText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplayPrintText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisplayPrintText, 155);
    lv_obj_set_y(ui_DisplayPrintText, 0);
    lv_obj_set_align(ui_DisplayPrintText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DisplayPrintText, "Output");
    lv_obj_set_style_text_color(ui_DisplayPrintText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DisplayPrintText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplayChartText = lv_label_create(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplayChartText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplayChartText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisplayChartText, -163);
    lv_obj_set_y(ui_DisplayChartText, 0);
    lv_obj_set_align(ui_DisplayChartText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DisplayChartText, "Chart");
    lv_obj_set_style_text_color(ui_DisplayChartText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DisplayChartText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningText = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RunningText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningText, 144);
    lv_obj_set_y(ui_RunningText, -17);
    lv_obj_set_align(ui_RunningText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_RunningText, "Running...");

    ui_SettingsButton = lv_imagebutton_create(ui_MainScreen);
    lv_imagebutton_set_src(ui_SettingsButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_settings_45dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_SettingsButton, 45);
    lv_obj_set_height(ui_SettingsButton, 45);
    lv_obj_set_x(ui_SettingsButton, -5);
    lv_obj_set_y(ui_SettingsButton, -3);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_BOTTOM_RIGHT);

    ui_StopPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_StopPanel, 480);
    lv_obj_set_height(ui_StopPanel, 30);
    lv_obj_set_x(ui_StopPanel, 0);
    lv_obj_set_y(ui_StopPanel, -25);
    lv_obj_set_align(ui_StopPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_StopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopText = lv_label_create(ui_StopPanel);
    lv_obj_set_width(ui_StopText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopText, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_StopText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrintLine1 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_PrintLine1, "");

    ui_PrintLine2 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine2, 0);
    lv_obj_set_y(ui_PrintLine2, 20);
    lv_label_set_text(ui_PrintLine2, "");

    ui_PrintLine3 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine3, 0);
    lv_obj_set_y(ui_PrintLine3, 40);
    lv_label_set_text(ui_PrintLine3, "");

    ui_PrintLine4 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine4, 0);
    lv_obj_set_y(ui_PrintLine4, 60);
    lv_label_set_text(ui_PrintLine4, "");

    ui_PrintLine5 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine5, 0);
    lv_obj_set_y(ui_PrintLine5, 80);
    lv_label_set_text(ui_PrintLine5, "");

    ui_PrintLine6 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine6, 0);
    lv_obj_set_y(ui_PrintLine6, 100);
    lv_label_set_text(ui_PrintLine6, "");

    ui_PrintLine7 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine7, 0);
    lv_obj_set_y(ui_PrintLine7, 120);
    lv_label_set_text(ui_PrintLine7, "");

    ui_PrintLine8 = lv_label_create(ui_PrintPanel);
    lv_obj_set_width(ui_PrintLine8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrintLine8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrintLine8, 0);
    lv_obj_set_y(ui_PrintLine8, 140);
    lv_label_set_text(ui_PrintLine8, "");

    ui_ULegend = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_ULegend);
    lv_obj_set_width(ui_ULegend, 120);
    lv_obj_set_height(ui_ULegend, 30);
    lv_obj_set_x(ui_ULegend, -35);
    lv_obj_set_y(ui_ULegend, 10);
    lv_obj_set_align(ui_ULegend, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_ULegend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UColour = lv_obj_create(ui_ULegend);
    lv_obj_set_width(ui_UColour, 20);
    lv_obj_set_height(ui_UColour, 20);
    lv_obj_set_align(ui_UColour, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_UColour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UColour, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_UColour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_UColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_UColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ULegendLabel = lv_label_create(ui_ULegend);
    lv_obj_set_width(ui_ULegendLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ULegendLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ULegendLabel, -12);
    lv_obj_set_y(ui_ULegendLabel, 0);
    lv_obj_set_align(ui_ULegendLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ULegendLabel, "Control Effort");
    lv_obj_set_style_text_color(ui_ULegendLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ULegendLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ULegendLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ELegend = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_ELegend);
    lv_obj_set_width(ui_ELegend, 120);
    lv_obj_set_height(ui_ELegend, 30);
    lv_obj_set_x(ui_ELegend, -35);
    lv_obj_set_y(ui_ELegend, 40);
    lv_obj_set_align(ui_ELegend, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_ELegend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EColour = lv_obj_create(ui_ELegend);
    lv_obj_set_width(ui_EColour, 20);
    lv_obj_set_height(ui_EColour, 20);
    lv_obj_set_align(ui_EColour, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_EColour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EColour, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EColour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ELegendLabel = lv_label_create(ui_ELegend);
    lv_obj_set_width(ui_ELegendLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ELegendLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ELegendLabel, -18);
    lv_obj_set_y(ui_ELegendLabel, 0);
    lv_obj_set_align(ui_ELegendLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ELegendLabel, "Error");
    lv_obj_set_style_text_color(ui_ELegendLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ELegendLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ELegendLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ELegendLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EncLegend = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_EncLegend);
    lv_obj_set_width(ui_EncLegend, 120);
    lv_obj_set_height(ui_EncLegend, 30);
    lv_obj_set_x(ui_EncLegend, -35);
    lv_obj_set_y(ui_EncLegend, 70);
    lv_obj_set_align(ui_EncLegend, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_EncLegend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EncColour = lv_obj_create(ui_EncLegend);
    lv_obj_set_width(ui_EncColour, 20);
    lv_obj_set_height(ui_EncColour, 20);
    lv_obj_set_align(ui_EncColour, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_EncColour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EncColour, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EncColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EncColour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EncColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EncColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EncLegendLabel = lv_label_create(ui_EncLegend);
    lv_obj_set_width(ui_EncLegendLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EncLegendLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EncLegendLabel, -5);
    lv_obj_set_y(ui_EncLegendLabel, 0);
    lv_obj_set_align(ui_EncLegendLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EncLegendLabel, "Encoders");
    lv_obj_set_style_text_color(ui_EncLegendLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EncLegendLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EncLegendLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EncLegendLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistLegend = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_DistLegend);
    lv_obj_set_width(ui_DistLegend, 120);
    lv_obj_set_height(ui_DistLegend, 30);
    lv_obj_set_x(ui_DistLegend, -35);
    lv_obj_set_y(ui_DistLegend, 100);
    lv_obj_set_align(ui_DistLegend, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_DistLegend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DistColour = lv_obj_create(ui_DistLegend);
    lv_obj_set_width(ui_DistColour, 20);
    lv_obj_set_height(ui_DistColour, 20);
    lv_obj_set_align(ui_DistColour, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_DistColour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DistColour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DistColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DistColour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DistColour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DistColour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistLegendLabel = lv_label_create(ui_DistLegend);
    lv_obj_set_width(ui_DistLegendLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DistLegendLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistLegendLabel, -7);
    lv_obj_set_y(ui_DistLegendLabel, 0);
    lv_obj_set_align(ui_DistLegendLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistLegendLabel, "Distance");
    lv_obj_set_style_text_color(ui_DistLegendLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DistLegendLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DistLegendLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DistLegendLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch, ui_event_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Chart = NULL;
    ui_PrintPanel = NULL;
    ui_DisplaySwap = NULL;
    ui_SwitchFrame = NULL;
    ui_Switch = NULL;
    ui_DisplayPrintText = NULL;
    ui_DisplayChartText = NULL;
    ui_RunningText = NULL;
    ui_SettingsButton = NULL;
    ui_StopPanel = NULL;
    ui_StopText = NULL;
    ui_PrintLine1 = NULL;
    ui_PrintLine2 = NULL;
    ui_PrintLine3 = NULL;
    ui_PrintLine4 = NULL;
    ui_PrintLine5 = NULL;
    ui_PrintLine6 = NULL;
    ui_PrintLine7 = NULL;
    ui_PrintLine8 = NULL;
    ui_ULegend = NULL;
    ui_UColour = NULL;
    ui_ULegendLabel = NULL;
    ui_ELegend = NULL;
    ui_EColour = NULL;
    ui_ELegendLabel = NULL;
    ui_EncLegend = NULL;
    ui_EncColour = NULL;
    ui_EncLegendLabel = NULL;
    ui_DistLegend = NULL;
    ui_DistColour = NULL;
    ui_DistLegendLabel = NULL;
}
