// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_Chart;
extern lv_obj_t * ui_Chart_Xaxis;
extern lv_obj_t * ui_Chart_Yaxis1;
extern lv_obj_t * ui_Chart_Yaxis2;
extern lv_obj_t * ui_PrintPanel;
extern lv_obj_t * ui_DisplaySwap;
extern lv_obj_t * ui_SwitchFrame;
extern void ui_event_Switch(lv_event_t * e);
extern lv_obj_t * ui_Switch;
extern lv_obj_t * ui_DisplayPrintText;
extern lv_obj_t * ui_DisplayChartText;
extern lv_obj_t * ui_RunningText;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_StopPanel;
extern lv_obj_t * ui_StopText;
extern lv_obj_t * ui_PrintLine1;
extern lv_obj_t * ui_PrintLine2;
extern lv_obj_t * ui_PrintLine3;
extern lv_obj_t * ui_PrintLine4;
extern lv_obj_t * ui_PrintLine5;
extern lv_obj_t * ui_PrintLine6;
extern lv_obj_t * ui_PrintLine7;
extern lv_obj_t * ui_PrintLine8;
extern lv_obj_t * ui_OnScreenStopButton;
extern lv_obj_t * ui_StopButtonText;
extern lv_obj_t * ui_Legend;
extern lv_obj_t * ui_Plot1Colour;
extern lv_obj_t * ui_Plot2Colour;
extern lv_obj_t * ui_Plot3Colour;
extern lv_obj_t * ui_Plot4Colour;
extern lv_obj_t * ui_Plot1Label;
extern lv_obj_t * ui_Plot2Label;
extern lv_obj_t * ui_Plot3Label;
extern lv_obj_t * ui_Plot4Label;

// CUSTOM VARIABLES & FUNCTIONS
extern lv_chart_series_t *series_U;
extern lv_chart_series_t *series_E;
extern lv_chart_series_t *series_LeftEnc;
extern lv_chart_series_t *series_RightEnc;
extern lv_chart_series_t *series_ArmEnc;
extern lv_chart_series_t *series_LeftDist;
extern lv_chart_series_t *series_RightDist;
extern void update_y_axis(int min, int max);
extern void lvgl_print(int line_number, char* text, ...);
extern void ui_event_OnScreenStopButton(lv_event_t * e);
extern void ShowChart();
extern volatile bool print_panel_visible;
extern char print_buffers[8][64];
extern bool print_dirty[8];

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

