// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#include "../include/ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Chart = NULL;
lv_obj_t * ui_Chart_Xaxis = NULL;
lv_obj_t * ui_Chart_Yaxis1 = NULL;
lv_obj_t * ui_Chart_Yaxis2 = NULL;
lv_obj_t * ui_PrintPanel = NULL;
lv_obj_t * ui_DisplaySwap = NULL;
lv_obj_t * ui_SwitchFrame = NULL;
lv_obj_t * ui_Switch = NULL;
lv_obj_t * ui_DisplayPrintText = NULL;
lv_obj_t * ui_DisplayChartText = NULL;
lv_obj_t * ui_RunningText = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_StopButtonPressedPanel = NULL;
lv_obj_t * ui_StopButtonPressedText = NULL;
lv_chart_series_t *series_U = NULL;
lv_chart_series_t *series_E = NULL;
lv_chart_series_t *series_Enc = NULL;
lv_chart_series_t *series_Dist = NULL;

// event functions
void ui_event_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PrintPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Chart, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_SettingsScreen_screen_init);
    }
}

// Custom Functions
void create_chart_series(void)
{
    if(series_U == NULL)
        series_U = lv_chart_add_series(ui_Chart, lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);

    if(series_E == NULL)
        series_E = lv_chart_add_series(ui_Chart, lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);

    if(series_Enc == NULL)
        series_Enc = lv_chart_add_series(ui_Chart, lv_color_hex(0x0000FF), LV_CHART_AXIS_PRIMARY_Y);

    if(series_Dist == NULL)
        series_Dist = lv_chart_add_series(ui_Chart, lv_color_hex(0xFFFF00), LV_CHART_AXIS_PRIMARY_Y);
}

// build functions
void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart = lv_chart_create(ui_MainScreen);
    lv_obj_set_width(ui_Chart, 420);
    lv_obj_set_height(ui_Chart, 185);
    lv_obj_set_x(ui_Chart, 30);
    lv_obj_set_y(ui_Chart, 5);
    lv_obj_add_flag(ui_Chart, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart, LV_CHART_TYPE_LINE);
    lv_obj_set_style_bg_color(ui_Chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Chart, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Chart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Chart, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart_Xaxis = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart,
                                                                  LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart_Xaxis, false);
    ui_Chart_Yaxis1 = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart_Yaxis1, 2, lv_pct(100));
    lv_obj_set_align(ui_Chart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart_Yaxis1, -2 - lv_obj_get_style_pad_left(ui_Chart,
                                                                 LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Yaxis1, 3, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart_Yaxis2 = lv_scale_create(ui_Chart);
    lv_scale_set_mode(ui_Chart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart,
                                                                  LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart_Yaxis2, 3, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart_Yaxis2, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart_Yaxis2, 2 >= 1 ? 2 : 1);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart, LV_MAX3(50, 2, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_PrintPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_PrintPanel, 420);
    lv_obj_set_height(ui_PrintPanel, 185);
    lv_obj_set_x(ui_PrintPanel, 30);
    lv_obj_set_y(ui_PrintPanel, 5);
    lv_obj_remove_flag(ui_PrintPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrintPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrintPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PrintPanel, lv_color_hex(0x3C3B3B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrintPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrintPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PrintPanel, lv_color_hex(0x3C3B3B), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PrintPanel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrintPanel, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_DisplaySwap = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplaySwap, 480);
    lv_obj_set_height(ui_DisplaySwap, 50);
    lv_obj_set_align(ui_DisplaySwap, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_DisplaySwap, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchFrame = lv_obj_create(ui_DisplaySwap);
    lv_obj_set_width(ui_SwitchFrame, 190);
    lv_obj_set_height(ui_SwitchFrame, 40);
    lv_obj_set_align(ui_SwitchFrame, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SwitchFrame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchFrame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchFrame, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch = lv_switch_create(ui_DisplaySwap);
    lv_obj_set_width(ui_Switch, 50);
    lv_obj_set_height(ui_Switch, 25);
    lv_obj_set_align(ui_Switch, LV_ALIGN_CENTER);

    ui_DisplayPrintText = lv_label_create(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplayPrintText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplayPrintText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisplayPrintText, 155);
    lv_obj_set_y(ui_DisplayPrintText, 0);
    lv_obj_set_align(ui_DisplayPrintText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DisplayPrintText, "Output");
    lv_obj_set_style_text_color(ui_DisplayPrintText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DisplayPrintText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplayChartText = lv_label_create(ui_DisplaySwap);
    lv_obj_set_width(ui_DisplayChartText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplayChartText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisplayChartText, -163);
    lv_obj_set_y(ui_DisplayChartText, 0);
    lv_obj_set_align(ui_DisplayChartText, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DisplayChartText, "Chart");
    lv_obj_set_style_text_color(ui_DisplayChartText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DisplayChartText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningText = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RunningText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningText, 144);
    lv_obj_set_y(ui_RunningText, -17);
    lv_obj_set_align(ui_RunningText, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_RunningText, "Running...");

    ui_SettingsButton = lv_imagebutton_create(ui_MainScreen);
    lv_imagebutton_set_src(ui_SettingsButton, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_settings_45dp_ffffff_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_SettingsButton, 45);
    lv_obj_set_height(ui_SettingsButton, 45);
    lv_obj_set_x(ui_SettingsButton, -5);
    lv_obj_set_y(ui_SettingsButton, -3);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_BOTTOM_RIGHT);

    ui_StopButtonPressedPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_StopButtonPressedPanel, 420);
    lv_obj_set_height(ui_StopButtonPressedPanel, 30);
    lv_obj_set_x(ui_StopButtonPressedPanel, 0);
    lv_obj_set_y(ui_StopButtonPressedPanel, -25);
    lv_obj_set_align(ui_StopButtonPressedPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButtonPressedPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_StopButtonPressedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopButtonPressedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopButtonPressedPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopButtonPressedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButtonPressedText = lv_label_create(ui_StopButtonPressedPanel);
    lv_obj_set_width(ui_StopButtonPressedText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopButtonPressedText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopButtonPressedText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopButtonPressedText, "STOP BUTTON PRESSED!");
    lv_obj_set_style_text_color(ui_StopButtonPressedText, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopButtonPressedText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch, ui_event_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);


    //Initialise chart series
    create_chart_series();
}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Chart = NULL;
    ui_PrintPanel = NULL;
    ui_DisplaySwap = NULL;
    ui_SwitchFrame = NULL;
    ui_Switch = NULL;
    ui_DisplayPrintText = NULL;
    ui_DisplayChartText = NULL;
    ui_RunningText = NULL;
    ui_SettingsButton = NULL;
    ui_StopButtonPressedPanel = NULL;
    ui_StopButtonPressedText = NULL;

}
