// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef UI_RUN_PROGRAM_H
#define UI_RUN_PROGRAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Run_Program
extern void ui_Run_Program_screen_init(void);
extern void ui_Run_Program_screen_destroy(void);
extern lv_obj_t * ui_Run_Program;
extern lv_obj_t * ui_User_Print_Output;
extern lv_obj_t * ui_Stop_Button_Text;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Data;
// extern lv_obj_t * ui_Placeholder_Graph;
extern lv_obj_t * ui_sensor_graph;
extern lv_chart_series_t * ui_series;
extern lv_obj_t * ui_Play_Button;
extern lv_obj_t * ui_Pause_Button;
extern void ui_event_Stop_Button(lv_event_t * e);
extern lv_obj_t * ui_Stop_Button;
// CUSTOM VARIABLES

extern int latest_sensor_value;
extern lv_timer_t *chart_timer;

void sample_sensor_task(void *param);
void chart_tick(lv_timer_t *timer);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

