// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#include "../include/ui.h"

lv_obj_t * ui_Run_Program = NULL;
lv_obj_t * ui_User_Print_Output = NULL;
lv_obj_t * ui_Stop_Button_Text = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Data = NULL;
lv_obj_t * ui_Placeholder_Graph = NULL;
lv_obj_t * ui_Play_Button = NULL;
lv_obj_t * ui_Pause_Button = NULL;
lv_obj_t * ui_Stop_Button = NULL;
// event funtions
void ui_event_Stop_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Stop_Button_Text, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_screen_change(&ui_Main_Menu, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 2500, &ui_Main_Menu_screen_init);
    }
}

// build funtions

void ui_Run_Program_screen_init(void)
{
    ui_Run_Program = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Run_Program, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Run_Program, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Run_Program, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_User_Print_Output = lv_obj_create(ui_Run_Program);
    lv_obj_set_width(ui_User_Print_Output, 236);
    lv_obj_set_height(ui_User_Print_Output, 190);
    lv_obj_set_x(ui_User_Print_Output, 4);
    lv_obj_set_y(ui_User_Print_Output, 21);
    lv_obj_set_align(ui_User_Print_Output, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_User_Print_Output, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_User_Print_Output, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_User_Print_Output, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Stop_Button_Text = lv_label_create(ui_User_Print_Output);
    lv_obj_set_width(ui_Stop_Button_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Stop_Button_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Stop_Button_Text, 1);
    lv_obj_set_y(ui_Stop_Button_Text, 75);
    lv_obj_set_align(ui_Stop_Button_Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Stop_Button_Text, "STOP BUTTON PRESSED!");
    lv_obj_add_flag(ui_Stop_Button_Text, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Stop_Button_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Stop_Button_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Stop_Button_Text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_User_Print_Output);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label5, "Kp = \nKi = \nu = \netc");

    ui_Data = lv_obj_create(ui_Run_Program);
    lv_obj_set_width(ui_Data, 231);
    lv_obj_set_height(ui_Data, 232);
    lv_obj_set_x(ui_Data, -4);
    lv_obj_set_y(ui_Data, 0);
    lv_obj_set_align(ui_Data, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Placeholder_Graph = lv_image_create(ui_Data);
    lv_image_set_src(ui_Placeholder_Graph, &ui_img_937709628);
    lv_obj_set_width(ui_Placeholder_Graph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Placeholder_Graph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Placeholder_Graph, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Placeholder_Graph, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Placeholder_Graph, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Placeholder_Graph, 80);

    ui_Play_Button = lv_imagebutton_create(ui_Run_Program);
    lv_imagebutton_set_src(ui_Play_Button, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_play_arrow_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_Play_Button, 64);
    lv_obj_set_height(ui_Play_Button, 64);
    lv_obj_set_x(ui_Play_Button, -11);
    lv_obj_set_y(ui_Play_Button, -7);

    ui_Pause_Button = lv_imagebutton_create(ui_Run_Program);
    lv_imagebutton_set_src(ui_Pause_Button, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_pause_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_Pause_Button, 64);
    lv_obj_set_height(ui_Pause_Button, 64);
    lv_obj_set_x(ui_Pause_Button, 33);
    lv_obj_set_y(ui_Pause_Button, -7);

    ui_Stop_Button = lv_imagebutton_create(ui_Run_Program);
    lv_imagebutton_set_src(ui_Stop_Button, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_stop_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png, NULL);
    lv_obj_set_width(ui_Stop_Button, 64);
    lv_obj_set_height(ui_Stop_Button, 64);
    lv_obj_set_x(ui_Stop_Button, -23);
    lv_obj_set_y(ui_Stop_Button, -7);
    lv_obj_set_align(ui_Stop_Button, LV_ALIGN_TOP_MID);

    lv_obj_add_event_cb(ui_Stop_Button, ui_event_Stop_Button, LV_EVENT_ALL, NULL);

}

void ui_Run_Program_screen_destroy(void)
{
    if(ui_Run_Program) lv_obj_del(ui_Run_Program);

    // NULL screen variables
    ui_Run_Program = NULL;
    ui_User_Print_Output = NULL;
    ui_Stop_Button_Text = NULL;
    ui_Label5 = NULL;
    ui_Data = NULL;
    ui_Placeholder_Graph = NULL;
    ui_Play_Button = NULL;
    ui_Pause_Button = NULL;
    ui_Stop_Button = NULL;

}
