// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#include "../include/ui.h"

lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Left_Distance_Sensor_Checkbox = NULL;
lv_obj_t * ui_Distance_sensor_checkbox_text = NULL;
lv_obj_t * ui_Motor_Checkbox = NULL;
lv_obj_t * ui_Motor_Checkbox_Text = NULL;
lv_obj_t * ui_Back_to_Menu_Text = NULL;
lv_obj_t * ui_Back_Arrow3 = NULL;
// event functions
void ui_event_Motor_Checkbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Placeholder_Graph, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_Placeholder_Graph, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Back_Arrow3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Main_Menu, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Main_Menu_screen_init);
    }
}

// build functions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left_Distance_Sensor_Checkbox = lv_checkbox_create(ui_Settings);
    lv_checkbox_set_text(ui_Left_Distance_Sensor_Checkbox, "Checkbox");
    lv_obj_set_width(ui_Left_Distance_Sensor_Checkbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left_Distance_Sensor_Checkbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left_Distance_Sensor_Checkbox, -149);
    lv_obj_set_y(ui_Left_Distance_Sensor_Checkbox, -61);
    lv_obj_set_align(ui_Left_Distance_Sensor_Checkbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Left_Distance_Sensor_Checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Distance_sensor_checkbox_text = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Distance_sensor_checkbox_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Distance_sensor_checkbox_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Distance_sensor_checkbox_text, -14);
    lv_obj_set_y(ui_Distance_sensor_checkbox_text, -61);
    lv_obj_set_align(ui_Distance_sensor_checkbox_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Distance_sensor_checkbox_text, "Display Distance Sensor Graph during test");
    lv_obj_set_style_text_color(ui_Distance_sensor_checkbox_text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Distance_sensor_checkbox_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor_Checkbox = lv_checkbox_create(ui_Settings);
    lv_checkbox_set_text(ui_Motor_Checkbox, "Checkbox");
    lv_obj_set_width(ui_Motor_Checkbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor_Checkbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor_Checkbox, -149);
    lv_obj_set_y(ui_Motor_Checkbox, -27);
    lv_obj_set_align(ui_Motor_Checkbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Motor_Checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Motor_Checkbox_Text = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Motor_Checkbox_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Motor_Checkbox_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Motor_Checkbox_Text, -18);
    lv_obj_set_y(ui_Motor_Checkbox_Text, -27);
    lv_obj_set_align(ui_Motor_Checkbox_Text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Motor_Checkbox_Text, "Display Motor Encoder Graph during test");
    lv_obj_set_style_text_color(ui_Motor_Checkbox_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Motor_Checkbox_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Motor_Checkbox_Text, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_to_Menu_Text = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Back_to_Menu_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_to_Menu_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_to_Menu_Text, 19);
    lv_obj_set_y(ui_Back_to_Menu_Text, 6);
    lv_label_set_text(ui_Back_to_Menu_Text, "Back to Menu");
    lv_obj_set_style_text_color(ui_Back_to_Menu_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back_to_Menu_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Arrow3 = lv_imagebutton_create(ui_Settings);
    lv_imagebutton_set_src(ui_Back_Arrow3, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_keyboard_arrow_left_30dp_1f1f1f_fill0_wght400_grad0_opsz24_png, NULL);
    lv_obj_set_width(ui_Back_Arrow3, 24);
    lv_obj_set_height(ui_Back_Arrow3, 26);
    lv_obj_set_x(ui_Back_Arrow3, -5);
    lv_obj_set_y(ui_Back_Arrow3, -2);

    lv_obj_add_event_cb(ui_Motor_Checkbox, ui_event_Motor_Checkbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Back_Arrow3, ui_event_Back_Arrow3, LV_EVENT_ALL, NULL);

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    ui_Left_Distance_Sensor_Checkbox = NULL;
    ui_Distance_sensor_checkbox_text = NULL;
    ui_Motor_Checkbox = NULL;
    ui_Motor_Checkbox_Text = NULL;
    ui_Back_to_Menu_Text = NULL;
    ui_Back_Arrow3 = NULL;

}
