// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_AdjustKp;
extern lv_obj_t * ui_KpSlider;
extern lv_obj_t * ui_KpLabel;
extern lv_obj_t * ui_KpMin;
extern lv_obj_t * ui_KpMax;
extern lv_obj_t * ui_AdjustKi;
extern lv_obj_t * ui_KiSlider;
extern lv_obj_t * ui_KiLabel;
extern lv_obj_t * ui_KiMin;
extern lv_obj_t * ui_KiMax;
extern lv_obj_t * ui_AdjustControllerGainsLabel;
extern lv_obj_t * ui_GraphSettingsLabel;
extern lv_obj_t * ui_GraphSettings;
extern lv_obj_t * ui_PlotUCheckbox;
extern lv_obj_t * ui_PlotECheckbox;
extern lv_obj_t * ui_PlotWheelEncCheckbox;
extern lv_obj_t * ui_PlotArmEncCheckbox;
extern lv_obj_t * ui_PlotLeftDistanceCheckbox;
extern lv_obj_t * ui_PlotRightDistanceCheckbox;
extern void ui_event_BackToMainButton(lv_event_t * e);
extern lv_obj_t * ui_BackToMainButton;
extern lv_obj_t * ui_GoBackLabel;
// CUSTOM VARIABLES & FUNCTIONS
extern void ui_event_PlotUCheckbox(lv_event_t * e);
extern void ui_event_PlotECheckbox(lv_event_t * e);
extern void ui_event_PlotWheelEncCheckbox(lv_event_t * e);
extern void ui_event_PlotArmEncCheckbox(lv_event_t * e);
extern void ui_event_PlotLeftDistanceCheckbox(lv_event_t * e);
extern void ui_event_PlotRightDistanceCheckbox(lv_event_t * e);
extern int current_y_min;
extern int current_y_max;
extern lv_obj_t * ui_StopPanel2;
extern lv_obj_t * ui_StopText2;
extern void PlotData(int sensor_name);
extern void ui_event_KpSlider(lv_event_t * e);
extern void ui_event_KiSlider(lv_event_t * e);
extern void setKp(double Kp_value);
extern void setKi(double Ki_value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

