// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef UI_SELECT_PROGRAM_H
#define UI_SELECT_PROGRAM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Select_Program
extern void ui_Select_Program_screen_init(void);
extern void ui_Select_Program_screen_destroy(void);
extern lv_obj_t * ui_Select_Program;
extern lv_obj_t * ui_Back_Text;
extern void ui_event_Back_Arrow(lv_event_t * e);
extern lv_obj_t * ui_Back_Arrow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

