// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#include "../include/ui.h"

lv_obj_t * ui_Select_Program = NULL;
lv_obj_t * ui_Back_Text = NULL;
lv_obj_t * ui_Back_Arrow = NULL;
// event functions
void ui_event_Back_Arrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Main_Menu, LV_SCR_LOAD_ANIM_FADE_OUT, 100, 0, &ui_Main_Menu_screen_init);
    }
}

// build functions

void ui_Select_Program_screen_init(void)
{
    ui_Select_Program = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Select_Program, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Select_Program, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Select_Program, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Text = lv_label_create(ui_Select_Program);
    lv_obj_set_width(ui_Back_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back_Text, 20);
    lv_obj_set_y(ui_Back_Text, 5);
    lv_label_set_text(ui_Back_Text, "Back to Menu");
    lv_obj_set_style_text_color(ui_Back_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back_Text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back_Arrow = lv_imagebutton_create(ui_Select_Program);
    lv_imagebutton_set_src(ui_Back_Arrow, LV_IMAGEBUTTON_STATE_RELEASED, NULL,
                           &ui_img_keyboard_arrow_left_30dp_1f1f1f_fill0_wght400_grad0_opsz24_png, NULL);
    lv_obj_set_width(ui_Back_Arrow, 24);
    lv_obj_set_height(ui_Back_Arrow, 26);
    lv_obj_set_x(ui_Back_Arrow, -5);
    lv_obj_set_y(ui_Back_Arrow, -2);

    lv_obj_add_event_cb(ui_Back_Arrow, ui_event_Back_Arrow, LV_EVENT_ALL, NULL);

}

void ui_Select_Program_screen_destroy(void)
{
    if(ui_Select_Program) lv_obj_del(ui_Select_Program);

    // NULL screen variables
    ui_Select_Program = NULL;
    ui_Back_Text = NULL;
    ui_Back_Arrow = NULL;

}
