// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#include "../include/ui.h"
#include <stdlib.h>

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_AdjustKp = NULL;
lv_obj_t * ui_KpSlider = NULL;
lv_obj_t * ui_KpLabel = NULL;
lv_obj_t * ui_KpMin = NULL;
lv_obj_t * ui_KpMax = NULL;
lv_obj_t * ui_AdjustKi = NULL;
lv_obj_t * ui_KiSlider = NULL;
lv_obj_t * ui_KiLabel = NULL;
lv_obj_t * ui_KiMin = NULL;
lv_obj_t * ui_KiMax = NULL;
lv_obj_t * ui_AdjustControllerGainsLabel = NULL;
lv_obj_t * ui_GraphSettingsLabel = NULL;
lv_obj_t * ui_GraphSettings = NULL;
lv_obj_t * ui_PlotUCheckbox = NULL;
lv_obj_t * ui_PlotECheckbox = NULL;
lv_obj_t * ui_PlotWheelEncCheckbox = NULL;
lv_obj_t * ui_PlotArmEncCheckbox = NULL;
lv_obj_t * ui_PlotLeftDistanceCheckbox = NULL;
lv_obj_t * ui_PlotRightDistanceCheckbox = NULL;
lv_obj_t * ui_BackToMainButton = NULL;
lv_obj_t * ui_GoBackLabel = NULL;
lv_obj_t * ui_StopPanel2 = NULL;
lv_obj_t * ui_StopText2 = NULL;
// Custom Variables

int current_y_min = 0;
int current_y_max = 100;
int legend_y_pos = 20;

// event functions
void ui_event_BackToMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MainScreen_screen_init);
    }
}

// Show/Hide control effort series
void ui_event_PlotUCheckbox(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_U, checked ? lv_color_hex(0xFF0000) : lv_color_hex(0x00000000)); //Red
    // _ui_flag_modify(ui_ULegend, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    // lv_obj_set_y(ui_ULegend, legend_y_pos);
    // if (checked) {
    //     legend_y_pos += 20;
    // } else {
    //     legend_y_pos -= 20;
    // }
}
// Show/Hide error series
void ui_event_PlotECheckbox(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_E, checked ? lv_color_hex(0x00FF00) : lv_color_hex(0x00000000)); //Green
}
// Show/Hide wheel encoder series
void ui_event_PlotWheelEncCheckbox(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_WheelEnc, checked ? lv_color_hex(0x0000FF) : lv_color_hex(0x00000000)); //Blue
}
// Show/Hide arm encoder series
void ui_event_PlotArmEncCheckbox(lv_event_t * e) {
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_ArmEnc, checked ? lv_color_hex(0xFF00FF) : lv_color_hex(0x00000000)); //Blue

}
// Show/Hide left distance sensor series
void ui_event_PlotLeftDistanceCheckbox(lv_event_t * e)
{
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_LeftDist, checked ? lv_color_hex(0xFFFFFF) : lv_color_hex(0x00000000)); //White
}
// Show/Hide Right distance sensor series
void ui_event_PlotRightDistanceCheckbox(lv_event_t * e) {
    lv_obj_t * obj = lv_event_get_target(e);
    bool checked = lv_obj_has_state(obj, LV_STATE_CHECKED);
    lv_chart_set_series_color(ui_Chart, series_RightDist, checked ? lv_color_hex(0xFFFF00) : lv_color_hex(0x00000000)); //White
}

// build functions
void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdjustKp = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_AdjustKp);
    lv_obj_set_width(ui_AdjustKp, 240);
    lv_obj_set_height(ui_AdjustKp, 60);
    lv_obj_set_x(ui_AdjustKp, 0);
    lv_obj_set_y(ui_AdjustKp, 45);
    lv_obj_remove_flag(ui_AdjustKp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KpSlider = lv_slider_create(ui_AdjustKp);
    lv_slider_set_value(ui_KpSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_KpSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_KpSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_KpSlider, 128);
    lv_obj_set_height(ui_KpSlider, 10);
    lv_obj_set_align(ui_KpSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_KpSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_KpSlider,
                                                                                               lv_obj_get_style_pad_right(ui_KpSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_KpLabel = lv_label_create(ui_AdjustKp);
    lv_obj_set_width(ui_KpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KpLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_KpLabel, "Adjust Kp");

    ui_KpMin = lv_label_create(ui_AdjustKp);
    lv_obj_set_width(ui_KpMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KpMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KpMin, 20);
    lv_obj_set_y(ui_KpMin, 0);
    lv_obj_set_align(ui_KpMin, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_KpMin, "0.1");

    ui_KpMax = lv_label_create(ui_AdjustKp);
    lv_obj_set_width(ui_KpMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KpMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KpMax, -30);
    lv_obj_set_y(ui_KpMax, 0);
    lv_obj_set_align(ui_KpMax, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_KpMax, "10");

    ui_AdjustKi = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_AdjustKi);
    lv_obj_set_width(ui_AdjustKi, 240);
    lv_obj_set_height(ui_AdjustKi, 60);
    lv_obj_set_x(ui_AdjustKi, 0);
    lv_obj_set_y(ui_AdjustKi, -80);
    lv_obj_set_align(ui_AdjustKi, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_AdjustKi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KiSlider = lv_slider_create(ui_AdjustKi);
    lv_slider_set_value(ui_KiSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_KiSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_KiSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_KiSlider, 128);
    lv_obj_set_height(ui_KiSlider, 10);
    lv_obj_set_align(ui_KiSlider, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_KiSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_KiSlider,
                                                                                               lv_obj_get_style_pad_right(ui_KiSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_KiLabel = lv_label_create(ui_AdjustKi);
    lv_obj_set_width(ui_KiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KiLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_KiLabel, "Adjust Ki\n");

    ui_KiMin = lv_label_create(ui_AdjustKi);
    lv_obj_set_width(ui_KiMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KiMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KiMin, 20);
    lv_obj_set_y(ui_KiMin, 0);
    lv_obj_set_align(ui_KiMin, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_KiMin, "0.1");

    ui_KiMax = lv_label_create(ui_AdjustKi);
    lv_obj_set_width(ui_KiMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KiMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KiMax, -35);
    lv_obj_set_y(ui_KiMax, 0);
    lv_obj_set_align(ui_KiMax, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_KiMax, "1");

    ui_AdjustControllerGainsLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_AdjustControllerGainsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustControllerGainsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AdjustControllerGainsLabel, 35);
    lv_obj_set_y(ui_AdjustControllerGainsLabel, 15);
    lv_label_set_text(ui_AdjustControllerGainsLabel, "Adjust Controller Gains:");

    ui_GraphSettingsLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_GraphSettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GraphSettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GraphSettingsLabel, -60);
    lv_obj_set_y(ui_GraphSettingsLabel, 15);
    lv_obj_set_align(ui_GraphSettingsLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_GraphSettingsLabel, "Graph Settings:");

    ui_GraphSettings = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_GraphSettings);
    lv_obj_set_width(ui_GraphSettings, 240);
    lv_obj_set_height(ui_GraphSettings, 180);
    lv_obj_set_x(ui_GraphSettings, 0);
    lv_obj_set_y(ui_GraphSettings, 15);
    lv_obj_set_align(ui_GraphSettings, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_GraphSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlotUCheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotUCheckbox, "Plot Control Effort");
    lv_obj_set_width(ui_PlotUCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotUCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotUCheckbox, 20);
    lv_obj_set_y(ui_PlotUCheckbox, 0);
    lv_obj_add_flag(ui_PlotUCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotECheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotECheckbox, "Plot Error");
    lv_obj_set_width(ui_PlotECheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotECheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotECheckbox, 20);
    lv_obj_set_y(ui_PlotECheckbox, 30);
    lv_obj_add_flag(ui_PlotECheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotWheelEncCheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotWheelEncCheckbox, "Plot Wheel Encoders");
    lv_obj_set_width(ui_PlotWheelEncCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotWheelEncCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotWheelEncCheckbox, 20);
    lv_obj_set_y(ui_PlotWheelEncCheckbox, 60);
    lv_obj_add_flag(ui_PlotWheelEncCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotArmEncCheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotArmEncCheckbox, "Plot Arm Encoder");
    lv_obj_set_width(ui_PlotArmEncCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotArmEncCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotArmEncCheckbox, 20);
    lv_obj_set_y(ui_PlotArmEncCheckbox, 90);
    lv_obj_add_flag(ui_PlotArmEncCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotLeftDistanceCheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotLeftDistanceCheckbox, "Plot Left Distance");
    lv_obj_set_width(ui_PlotLeftDistanceCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotLeftDistanceCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotLeftDistanceCheckbox, 20);
    lv_obj_set_y(ui_PlotLeftDistanceCheckbox, 120);
    lv_obj_add_flag(ui_PlotLeftDistanceCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotRightDistanceCheckbox = lv_checkbox_create(ui_GraphSettings);
    lv_checkbox_set_text(ui_PlotRightDistanceCheckbox, "Plot Right Distance");
    lv_obj_set_width(ui_PlotRightDistanceCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotRightDistanceCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotRightDistanceCheckbox, 20);
    lv_obj_set_y(ui_PlotRightDistanceCheckbox, 150);
    lv_obj_add_flag(ui_PlotRightDistanceCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BackToMainButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BackToMainButton, 160);
    lv_obj_set_height(ui_BackToMainButton, 50);
    lv_obj_set_x(ui_BackToMainButton, 40);
    lv_obj_set_y(ui_BackToMainButton, -20);
    lv_obj_set_align(ui_BackToMainButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BackToMainButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackToMainButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainButton, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopPanel2 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_StopPanel2, 480);
    lv_obj_set_height(ui_StopPanel2, 30);
    lv_obj_set_x(ui_StopPanel2, 0);
    lv_obj_set_y(ui_StopPanel2, -25);
    lv_obj_set_align(ui_StopPanel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopPanel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_StopPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopText2 = lv_label_create(ui_StopPanel2);
    lv_obj_set_width(ui_StopText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopText2, "STOP BUTTON PRESSED!");
    lv_obj_set_style_text_color(ui_StopText2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackLabel = lv_label_create(ui_BackToMainButton);
    lv_obj_set_width(ui_GoBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GoBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GoBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GoBackLabel, "Go Back");


    lv_obj_add_event_cb(ui_BackToMainButton, ui_event_BackToMainButton, LV_EVENT_ALL, NULL);

    // Event callbacks for graph series checkboxes
    lv_obj_add_event_cb(ui_PlotUCheckbox, ui_event_PlotUCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotECheckbox, ui_event_PlotECheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotWheelEncCheckbox, ui_event_PlotWheelEncCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotArmEncCheckbox, ui_event_PlotArmEncCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotLeftDistanceCheckbox, ui_event_PlotLeftDistanceCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotRightDistanceCheckbox, ui_event_PlotRightDistanceCheckbox, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_AdjustKp = NULL;
    ui_KpSlider = NULL;
    ui_KpLabel = NULL;
    ui_KpMin = NULL;
    ui_KpMax = NULL;
    ui_AdjustKi = NULL;
    ui_KiSlider = NULL;
    ui_KiLabel = NULL;
    ui_KiMin = NULL;
    ui_KiMax = NULL;
    ui_AdjustControllerGainsLabel = NULL;
    ui_GraphSettingsLabel = NULL;
    ui_GraphSettings = NULL;
    ui_PlotUCheckbox = NULL;
    ui_PlotECheckbox = NULL;
    ui_PlotWheelEncCheckbox = NULL;
    ui_PlotArmEncCheckbox = NULL;
    ui_PlotLeftDistanceCheckbox = NULL;
    ui_PlotRightDistanceCheckbox = NULL;
    ui_BackToMainButton = NULL;
    ui_GoBackLabel = NULL;
    ui_StopPanel2 = NULL;
    ui_StopText2 = NULL;
}
