// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Left_Distance_Sensor_Checkbox;
extern lv_obj_t * ui_Distance_sensor_checkbox_text;
extern void ui_event_Motor_Checkbox(lv_event_t * e);
extern lv_obj_t * ui_Motor_Checkbox;
extern lv_obj_t * ui_Motor_Checkbox_Text;
extern lv_obj_t * ui_Back_to_Menu_Text;
extern void ui_event_Back_Arrow3(lv_event_t * e);
extern lv_obj_t * ui_Back_Arrow3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

