// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_AdjustValuesLabel;
extern lv_obj_t * ui_DisplaySeriesLabel;
extern lv_obj_t * ui_CheckboxesContainer;
extern lv_obj_t * ui_PlotLeftEncCheckbox;
extern lv_obj_t * ui_PlotRightEncCheckbox;
extern lv_obj_t * ui_PlotArmEncCheckbox;
extern lv_obj_t * ui_PlotSonarCheckbox;
extern lv_obj_t * ui_BackToMainButton;
extern lv_obj_t * ui_GoBackLabel;
extern lv_obj_t * ui_AdjustGainsContainer;
extern lv_obj_t * ui_Slot1Label;
extern lv_obj_t * ui_Slot2Label;
extern lv_obj_t * ui_Slot3Label;
extern lv_obj_t * ui_Slot1Button;
extern lv_obj_t * ui_AdjustSlot1Label;
extern lv_obj_t * ui_Slot2Button;
extern lv_obj_t * ui_AdjustSlot2Label;
extern lv_obj_t * ui_Slot3Button;
extern lv_obj_t * ui_AdjustSlot3Label;
extern lv_obj_t * ui_NumPad;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonText1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_ButtonText2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_ButtonText3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_ButtonText4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_ButtonText5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_ButtonText6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_ButtonText7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_ButtonText8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_ButtonText9;
extern lv_obj_t * ui_Button0;
extern lv_obj_t * ui_ButtonText0;
extern lv_obj_t * ui_ButtonDot;
extern lv_obj_t * ui_ButtonTextDot;
extern lv_obj_t * ui_ButtonDel;
extern lv_obj_t * ui_ButtonTextDel;
extern lv_obj_t * ui_ButtonDone;
extern lv_obj_t * ui_ButtonTextDone;
extern lv_obj_t * ui_GraphSettingsContainer;
extern lv_obj_t * ui_PlottingRateLabel;
extern lv_obj_t * ui_PlottingRateDropdown;
extern lv_obj_t * ui_StopPanel2;
extern lv_obj_t * ui_StopText2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
