// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#include "ui.h"
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include "main.h"
#include "../src/Student_Code.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_AdjustValuesLabel = NULL;
lv_obj_t * ui_DisplaySeriesLabel = NULL;
lv_obj_t * ui_CheckboxesContainer = NULL;
lv_obj_t * ui_PlotLeftEncCheckbox = NULL;
lv_obj_t * ui_PlotRightEncCheckbox = NULL;
lv_obj_t * ui_PlotArmEncCheckbox = NULL;
lv_obj_t * ui_PlotLeftDistanceCheckbox = NULL;
lv_obj_t * ui_PlotRightDistanceCheckbox = NULL;
lv_obj_t * ui_BackToMainButton = NULL;
lv_obj_t * ui_GoBackLabel = NULL;
lv_obj_t * ui_AdjustGainsContainer = NULL;
lv_obj_t * ui_Slot1Label = NULL;
lv_obj_t * ui_Slot2Label = NULL;
lv_obj_t * ui_Slot3Label = NULL;
lv_obj_t * ui_Slot1Button = NULL;
lv_obj_t * ui_AdjustSlot1Label = NULL;
lv_obj_t * ui_Slot2Button = NULL;
lv_obj_t * ui_AdjustSlot2Label = NULL;
lv_obj_t * ui_Slot3Button = NULL;
lv_obj_t * ui_AdjustSlot3Label = NULL;
lv_obj_t * ui_NumPad = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_ButtonText1 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_ButtonText2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_ButtonText3 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_ButtonText4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_ButtonText5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_ButtonText6 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_ButtonText7 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_ButtonText8 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_ButtonText9 = NULL;
lv_obj_t * ui_Button0 = NULL;
lv_obj_t * ui_ButtonText0 = NULL;
lv_obj_t * ui_ButtonDot = NULL;
lv_obj_t * ui_ButtonTextDot = NULL;
lv_obj_t * ui_ButtonDel = NULL;
lv_obj_t * ui_ButtonTextDel = NULL;
lv_obj_t * ui_ButtonDone = NULL;
lv_obj_t * ui_ButtonTextDone = NULL;
lv_obj_t * ui_GraphSettingsContainer = NULL;
lv_obj_t * ui_PlottingRateLabel = NULL;
lv_obj_t * ui_PlottingRateDropdown = NULL;
lv_obj_t * ui_StopPanel2 = NULL;
lv_obj_t * ui_StopText2 = NULL;
// Custom Variables
int current_y_min = 0;
int current_y_max = 100;
bool plot_u_enabled = false;
bool plot_e_enabled = false;
bool plot_left_enc_enabled = false;
bool plot_right_enc_enabled = false;
bool plot_arm_enabled = false;
bool plot_left_dist_enabled = false;
bool plot_right_dist_enabled = false;
numpad_ctx_t numpad_ctx;
int plotting_rate = 100;
variable_slot_t variable_slots[3];
bool numpad_is_open = false;       // Tracks if the Numpad is on screen
void * current_target_ptr = NULL;  // Tracks exactly which variable we are editing
uint32_t last_config_time = 0;


// event functions
void ui_event_BackToMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MainScreen_screen_init);
    }
}


void ui_event_Slot1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_clear_flag(ui_NumPad, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_state(ui_PlottingRateDropdown, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot1Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot2Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot3Button, LV_STATE_DISABLED);

        if (variable_slots[0].active) {
        // Open the Numpad targeting the stored pointer
        NumpadOpen(
            variable_slots[0].var_ptr, 
            variable_slots[0].type, 
            variable_slots[0].slot_label, 
            variable_slots[0].name, 
            6, 2
        );
    }

    }
}

void ui_event_Slot2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_clear_flag(ui_NumPad, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_state(ui_PlottingRateDropdown, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot1Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot2Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot3Button, LV_STATE_DISABLED);

        if (variable_slots[1].active) {
        // Open the Numpad targeting the stored pointer
        NumpadOpen(
            variable_slots[1].var_ptr, 
            variable_slots[1].type, 
            variable_slots[1].slot_label, 
            variable_slots[1].name, 
            6, 2
        );
    }
    }
}

void ui_event_Slot3Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_clear_flag(ui_NumPad, LV_OBJ_FLAG_HIDDEN);
        lv_obj_add_state(ui_PlottingRateDropdown, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot1Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot2Button, LV_STATE_DISABLED);
        lv_obj_add_state(ui_Slot3Button, LV_STATE_DISABLED);
        
        if (variable_slots[2].active) {
        // Open the Numpad targeting the stored pointer
        NumpadOpen(
            variable_slots[2].var_ptr, 
            variable_slots[2].type, 
            variable_slots[2].slot_label, 
            variable_slots[2].name, 
            6, 2
        );
    }
    }
}

void ui_event_ButtonDone(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_obj_add_flag(ui_NumPad, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_state(ui_PlottingRateDropdown, LV_STATE_DISABLED);
        lv_obj_clear_state(ui_Slot1Button, LV_STATE_DISABLED);
        lv_obj_clear_state(ui_Slot2Button, LV_STATE_DISABLED);
        lv_obj_clear_state(ui_Slot3Button, LV_STATE_DISABLED);
    //Reset the label color to White
    if (numpad_ctx.target_label != NULL) {
        lv_obj_set_style_text_color(numpad_ctx.target_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // Safety check: ensure we have a valid pointer
    if (numpad_ctx.target_value == NULL) return;

    // If the student deleted everything, force it to zero
    if (strlen(numpad_ctx.buffer) == 0) {
        strcpy(numpad_ctx.buffer, "0");
    }

    if (numpad_ctx.type == TYPE_DOUBLE) {
        double *val = (double *)numpad_ctx.target_value;
        *val = atof(numpad_ctx.buffer); // Convert string to double
    } 
    else if (numpad_ctx.type == TYPE_INT) {
        int *val = (int *)numpad_ctx.target_value;
        *val = atoi(numpad_ctx.buffer); // Convert string to int
    }

    numpad_is_open = false;      // Reset the flag
    current_target_ptr = NULL;   // Clear the pointer
    }
}

void ui_event_PlottingRateDropdown(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        char selected[8];
        lv_dropdown_get_selected_str(ui_PlottingRateDropdown, selected, sizeof(selected));
        plotting_rate = atoi(selected);

        if(graph_timer) {
            lv_timer_set_period(graph_timer, plotting_rate);
        }
    }
}

// Show/Hide left wheel encoder series
void ui_event_PlotLeftEncCheckbox(lv_event_t * e) {
     plot_left_enc_enabled = lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED);
}
// Show/Hide right wheel encoder series
void ui_event_PlotRightEncCheckbox(lv_event_t * e) {
     plot_right_enc_enabled = lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED);
}
// Show/Hide arm encoder series
void ui_event_PlotArmEncCheckbox(lv_event_t * e) {
     plot_arm_enabled = lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED);
}
// Show/Hide left distance sensor series
void ui_event_PlotLeftDistanceCheckbox(lv_event_t * e) {
     plot_left_dist_enabled = lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED);
}
// Show/Hide Right distance sensor series
void ui_event_PlotRightDistanceCheckbox(lv_event_t * e) {
     plot_right_dist_enabled = lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED);
}

/* CUSTOM FUNCTIONS*/

// A function that can be used to check a box automatically to plot data
void PlotSensor(int data_name) {
    if (data_name == LeftDistance) {
        lv_obj_add_state(ui_PlotLeftDistanceCheckbox, LV_STATE_CHECKED);
    } else if (data_name == RightDistance) {
        lv_obj_add_state(ui_PlotRightDistanceCheckbox, LV_STATE_CHECKED);
    } else if (data_name == LeftEncoder) {
        lv_obj_add_state(ui_PlotLeftEncCheckbox, LV_STATE_CHECKED);
    } else if (data_name == RightEncoder) {
        lv_obj_add_state(ui_PlotRightEncCheckbox, LV_STATE_CHECKED);
    } else if (data_name == ArmEncoder) {
        lv_obj_add_state(ui_PlotArmEncCheckbox, LV_STATE_CHECKED);
    }
}

void ClearSeriesTimer(lv_timer_t * t) {
    // Retrieve the series pointer from the timer's user_data
    lv_chart_series_t * series = (lv_chart_series_t *)t->user_data;
    if (series) {
        lv_chart_set_all_value(ui_Chart, series, LV_CHART_POINT_NONE);
    }}

void ClearSeries(lv_chart_series_t * series) {
    if (!series) return;
    lv_timer_t * t = lv_timer_create(ClearSeriesTimer, 20, series);
    lv_timer_set_repeat_count(t, 1);
}

void NumpadOpen(void *value, numpad_data_type_t type, lv_obj_t *label, const char *prefix, int max_len, int max_dec){
    // Store the label data
    numpad_ctx.target_value = value;
    numpad_ctx.type = type;
    numpad_ctx.target_label = label;
    numpad_ctx.prefix = prefix;

    // Store the limits
    numpad_ctx.max_length = max_len;
    numpad_ctx.max_decimals = max_dec;

    // formatting based on type
    if (type == TYPE_DOUBLE) {
        double *d_ptr = (double *)value;
        snprintf(numpad_ctx.buffer, sizeof(numpad_ctx.buffer), "%.2f", *d_ptr);
    } 
    else if (type == TYPE_INT) {
        int *i_ptr = (int *)value;
        snprintf(numpad_ctx.buffer, sizeof(numpad_ctx.buffer), "%d", *i_ptr);
    }

    current_target_ptr = value;  // Set the target pointer
    numpad_is_open = true;       // Set the flag

    lv_obj_set_style_text_color(numpad_ctx.target_label, lv_color_hex(0xF44336), LV_PART_MAIN | LV_STATE_DEFAULT);

    UpdateTargetLabel();
}

void NumpadButtonEvent(lv_event_t *e)
{
    const char *key = lv_event_get_user_data(e);
    size_t len = strlen(numpad_ctx.buffer);
    char *decimal_ptr = strchr(numpad_ctx.buffer, '.');

    // --- HANDLE DELETE ---
    if (strcmp(key, "DEL") == 0) {
        if (len > 0) {
            numpad_ctx.buffer[len - 1] = '\0';
        }
    } 
    // --- HANDLE INPUT ---
    else {
        // 1. TOTAL LENGTH CHECK
        // If we reached the max length, do nothing.
        if (len >= numpad_ctx.max_length) {
            return; 
        }
        // 2. DECIMAL POINT CHECK
        if (key[0] == '.') {
            // If we already have a decimal, do nothing
            if (decimal_ptr != NULL) return;
            
            // If this is an Integer type variable, block decimals entirely
            if (numpad_ctx.type == TYPE_INT) return;
        }
        // 3. DECIMAL PRECISION CHECK
        // If we are currently typing digits AFTER the decimal point
        if (decimal_ptr != NULL && key[0] != '.') {
            // Calculate how many digits are currently after the dot
            // ptr points to '.', so ptr+1 is the first digit after it
            int decimals_existing = strlen(decimal_ptr + 1);

            if (decimals_existing >= numpad_ctx.max_decimals) {
                return;
            }
        }
        // 4. APPEND IF SAFE
        if (len < sizeof(numpad_ctx.buffer) - 1) {
            strcat(numpad_ctx.buffer, key);
        }
    } 
    UpdateTargetLabel();
}

void UpdateTargetLabel(void)
{
if (numpad_ctx.target_label == NULL) return;

    lv_label_set_text_fmt(numpad_ctx.target_label, "%s = %s", 
                         numpad_ctx.prefix, numpad_ctx.buffer);
}

// A helper function - for finding the closest value in the dropdown to the target value
int FindClosestDropdownIndex(lv_obj_t * dropdown, int target_value) {
    const char * options = lv_dropdown_get_options(dropdown);
    if (options == NULL) return 0;

    // Create a local copy because strtok modifies the string
    char options_copy[256]; 
    strncpy(options_copy, options, sizeof(options_copy) - 1);
    options_copy[sizeof(options_copy) - 1] = '\0';

    int closest_index = 0;
    int current_index = 0;
    int min_diff = INT32_MAX;

    // Split the string by the newline character
    char * token = strtok(options_copy, "\n");
    while (token != NULL) {
        int option_val = atoi(token);
        int diff = abs(option_val - target_value);

        if (diff < min_diff) {
            min_diff = diff;
            closest_index = current_index;
        }

        token = strtok(NULL, "\n");
        current_index++;
    }

    return closest_index;
}

// A function to set the plotting rate based on a given value
void SetPlottingRate(int rate_ms) {
    if (!ui_PlottingRateDropdown) return;

    // 1. Find the closest index and snap the UI to it
    int idx = FindClosestDropdownIndex(ui_PlottingRateDropdown, rate_ms);
    lv_dropdown_set_selected(ui_PlottingRateDropdown, idx);

    // 2. Get the actual string value of that index to update our variable
    char buf[16];
    lv_dropdown_get_selected_str(ui_PlottingRateDropdown, buf, sizeof(buf));
    plotting_rate = atoi(buf);

    // 3. Update the hardware timer
    if (graph_timer) {
        lv_timer_set_period(graph_timer, plotting_rate);
    }
}

// A function students can use to configure a variable adjustment slot
void _InternalConfig(int slot_num, void * var, numpad_data_type_t type, const char * name) {
    
    int index = slot_num - 1;
    if (index < 0 || index >= 3) return;

    // Check if slots need to be reset
    if (millis() - last_config_time > 100) {
        ResetVariableSlots();
    }
    last_config_time = millis();

    // Reset the abandonment counter
    variable_slots[index].cycles_since_update = 0;

    if (variable_slots[index].var_ptr != var || strcmp(variable_slots[index].name, name) != 0) {
        variable_slots[index].var_ptr = var;
        variable_slots[index].type = type;
        variable_slots[index].active = true;
        
        // Name truncation logic...
        if (strlen(name) > 16) {
            strncpy(variable_slots[index].name, name, 13);
            variable_slots[index].name[13] = '\0';
            strcat(variable_slots[index].name, "...");
        } else {
            strcpy(variable_slots[index].name, name);
        }
    }

    // Initial update
    char buffer[64];
    if (type == TYPE_DOUBLE) {
        snprintf(buffer, sizeof(buffer), "%s = %.2f", name, *(double*)var);
    } else {
        snprintf(buffer, sizeof(buffer), "%s = %d", name, *(int*)var);
    }
    
    if (variable_slots[index].slot_label) {
        lv_label_set_text(variable_slots[index].slot_label, buffer);
    }
}

// A timer function to refresh all variable labels
void RefreshVariableLabels(lv_timer_t * t) {
    if (_stopflag == 1) return; // Do not update if in stop mode

    for (int i = 0; i < 3; i++) {

        // Safety: skip if not active, no pointer, or no label
        if (!variable_slots[i].active || variable_slots[i].var_ptr == NULL || variable_slots[i].slot_label == NULL) {
            continue; 
        }

        // GUARDRAIL: Do not overwrite the label if the student is currently typing!
        if (numpad_is_open && (current_target_ptr == (void*)variable_slots[i].var_ptr)) {
            continue; 
        }

        char buffer[64];
        if (variable_slots[i].type == TYPE_DOUBLE) {
            // Cast the void pointer to double* then dereference
            double val = *(double*)variable_slots[i].var_ptr;
            snprintf(buffer, sizeof(buffer), "%s = %.2f", variable_slots[i].name, val);
        } else {
            // Cast the void pointer to int* then dereference
            int val = *(int*)variable_slots[i].var_ptr;
            snprintf(buffer, sizeof(buffer), "%s = %d", variable_slots[i].name, val);
        }

        lv_label_set_text(variable_slots[i].slot_label, buffer);
    }
}

void ResetVariableSlots() {
    for (int i = 0; i < 3; i++) {
        variable_slots[i].active = false;
        variable_slots[i].var_ptr = NULL; 
        if (variable_slots[i].slot_label) {
            lv_label_set_text(variable_slots[i].slot_label, " - ");
        }
    }
}

// build functions
void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x0C0C48), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AdjustValuesLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_AdjustValuesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustValuesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AdjustValuesLabel, -115);
    lv_obj_set_y(ui_AdjustValuesLabel, 10);
    lv_obj_set_align(ui_AdjustValuesLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AdjustValuesLabel, "Adjust Values:");

    ui_DisplaySeriesLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_DisplaySeriesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisplaySeriesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisplaySeriesLabel, -65);
    lv_obj_set_y(ui_DisplaySeriesLabel, 10);
    lv_obj_set_align(ui_DisplaySeriesLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_DisplaySeriesLabel, "Display Series:");

    ui_CheckboxesContainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_CheckboxesContainer);
    lv_obj_set_width(ui_CheckboxesContainer, 220);
    lv_obj_set_height(ui_CheckboxesContainer, 200);
    lv_obj_set_x(ui_CheckboxesContainer, 0);
    lv_obj_set_y(ui_CheckboxesContainer, 15);
    lv_obj_set_align(ui_CheckboxesContainer, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_CheckboxesContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlotLeftEncCheckbox = lv_checkbox_create(ui_CheckboxesContainer);
    lv_checkbox_set_text(ui_PlotLeftEncCheckbox, "Plot Left Encoder");
    lv_obj_set_width(ui_PlotLeftEncCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotLeftEncCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotLeftEncCheckbox, 20);
    lv_obj_set_y(ui_PlotLeftEncCheckbox, 0);
    lv_obj_add_flag(ui_PlotLeftEncCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


    ui_PlotRightEncCheckbox = lv_checkbox_create(ui_CheckboxesContainer);
    lv_checkbox_set_text(ui_PlotRightEncCheckbox, "Plot Right Encoder");
    lv_obj_set_width(ui_PlotRightEncCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotRightEncCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotRightEncCheckbox, 20);
    lv_obj_set_y(ui_PlotRightEncCheckbox, 28);
    lv_obj_add_flag(ui_PlotRightEncCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotArmEncCheckbox = lv_checkbox_create(ui_CheckboxesContainer);
    lv_checkbox_set_text(ui_PlotArmEncCheckbox, "Plot Arm Encoder");
    lv_obj_set_width(ui_PlotArmEncCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotArmEncCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotArmEncCheckbox, 20);
    lv_obj_set_y(ui_PlotArmEncCheckbox, 56);
    lv_obj_add_flag(ui_PlotArmEncCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotLeftDistanceCheckbox = lv_checkbox_create(ui_CheckboxesContainer);
    lv_checkbox_set_text(ui_PlotLeftDistanceCheckbox, "Plot Left Distance");
    lv_obj_set_width(ui_PlotLeftDistanceCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotLeftDistanceCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotLeftDistanceCheckbox, 20);
    lv_obj_set_y(ui_PlotLeftDistanceCheckbox, 84);
    lv_obj_add_flag(ui_PlotLeftDistanceCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_PlotRightDistanceCheckbox = lv_checkbox_create(ui_CheckboxesContainer);
    lv_checkbox_set_text(ui_PlotRightDistanceCheckbox, "Plot Right Distance");
    lv_obj_set_width(ui_PlotRightDistanceCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlotRightDistanceCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlotRightDistanceCheckbox, 20);
    lv_obj_set_y(ui_PlotRightDistanceCheckbox, 112);
    lv_obj_add_flag(ui_PlotRightDistanceCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BackToMainButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BackToMainButton, 160);
    lv_obj_set_height(ui_BackToMainButton, 50);
    lv_obj_set_x(ui_BackToMainButton, -35);
    lv_obj_set_y(ui_BackToMainButton, -10);
    lv_obj_set_align(ui_BackToMainButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BackToMainButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BackToMainButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackToMainButton, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackToMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackToMainButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackToMainButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackToMainButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GoBackLabel = lv_label_create(ui_BackToMainButton);
    lv_obj_set_width(ui_GoBackLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GoBackLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GoBackLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GoBackLabel, "Go Back");

    ui_AdjustGainsContainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_AdjustGainsContainer, 250);
    lv_obj_set_height(ui_AdjustGainsContainer, 160);
    lv_obj_set_x(ui_AdjustGainsContainer, 0);
    lv_obj_set_y(ui_AdjustGainsContainer, 20);
    lv_obj_remove_flag(ui_AdjustGainsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slot1Label = lv_label_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot1Label, -40);
    lv_obj_set_y(ui_Slot1Label, 27);
    lv_obj_set_align(ui_Slot1Label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Slot1Label, " - ");

    ui_Slot2Label = lv_label_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot2Label, -40);
    lv_obj_set_y(ui_Slot2Label, 77);
    lv_obj_set_align(ui_Slot2Label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Slot2Label, " - ");

    ui_Slot3Label = lv_label_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot3Label, -40);
    lv_obj_set_y(ui_Slot3Label, 127);
    lv_obj_set_align(ui_Slot3Label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Slot3Label, " - ");

    ui_Slot1Button = lv_button_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot1Button, 80);
    lv_obj_set_height(ui_Slot1Button, 40);
    lv_obj_set_x(ui_Slot1Button, 0);
    lv_obj_set_y(ui_Slot1Button, 15);
    lv_obj_set_align(ui_Slot1Button, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Slot1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Slot1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slot1Button, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slot1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slot1Button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slot1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slot1Button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_state(ui_Slot1Button, LV_STATE_DISABLED);

    ui_AdjustSlot1Label = lv_label_create(ui_Slot1Button);
    lv_obj_set_width(ui_AdjustSlot1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustSlot1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AdjustSlot1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AdjustSlot1Label, "Adjust");

    ui_Slot2Button = lv_button_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot2Button, 80);
    lv_obj_set_height(ui_Slot2Button, 40);
    lv_obj_set_x(ui_Slot2Button, 0);
    lv_obj_set_y(ui_Slot2Button, 65);
    lv_obj_set_align(ui_Slot2Button, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Slot2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Slot2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slot2Button, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slot2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slot2Button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slot2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slot2Button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_state(ui_Slot2Button, LV_STATE_DISABLED);

    ui_AdjustSlot2Label = lv_label_create(ui_Slot2Button);
    lv_obj_set_width(ui_AdjustSlot2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustSlot2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AdjustSlot2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AdjustSlot2Label, "Adjust");

    ui_Slot3Button = lv_button_create(ui_AdjustGainsContainer);
    lv_obj_set_width(ui_Slot3Button, 80);
    lv_obj_set_height(ui_Slot3Button, 40);
    lv_obj_set_x(ui_Slot3Button, 0);
    lv_obj_set_y(ui_Slot3Button, 115);
    lv_obj_set_align(ui_Slot3Button, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Slot3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Slot3Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Slot3Button, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slot3Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slot3Button, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slot3Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Slot3Button, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_state(ui_Slot3Button, LV_STATE_DISABLED);

    ui_AdjustSlot3Label = lv_label_create(ui_Slot3Button);
    lv_obj_set_width(ui_AdjustSlot3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustSlot3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AdjustSlot3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AdjustSlot3Label, "Adjust");

    ui_NumPad = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_NumPad, 220);
    lv_obj_set_height(ui_NumPad, 230);
    lv_obj_set_x(ui_NumPad, -5);
    lv_obj_set_y(ui_NumPad, 0);
    lv_obj_set_align(ui_NumPad, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_NumPad, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_NumPad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NumPad, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NumPad, lv_color_hex(0x2F2F2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NumPad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NumPad, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NumPad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button1, 65);
    lv_obj_set_height(ui_Button1, 40);
    lv_obj_set_x(ui_Button1, -10);
    lv_obj_set_y(ui_Button1, -10);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_ButtonText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText1, "1");

    ui_Button2 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button2, 65);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, 60);
    lv_obj_set_y(ui_Button2, -10);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_ButtonText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText2, "2");

    ui_Button3 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button3, 65);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 130);
    lv_obj_set_y(ui_Button3, -10);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_ButtonText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText3, "3");

    ui_Button4 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button4, 65);
    lv_obj_set_height(ui_Button4, 40);
    lv_obj_set_x(ui_Button4, -10);
    lv_obj_set_y(ui_Button4, 35);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_ButtonText4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText4, "4");

    ui_Button5 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button5, 65);
    lv_obj_set_height(ui_Button5, 40);
    lv_obj_set_x(ui_Button5, 60);
    lv_obj_set_y(ui_Button5, 35);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText5 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_ButtonText5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText5, "5");

    ui_Button6 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button6, 65);
    lv_obj_set_height(ui_Button6, 40);
    lv_obj_set_x(ui_Button6, 130);
    lv_obj_set_y(ui_Button6, 35);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText6 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_ButtonText6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText6, "6");

    ui_Button7 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button7, 65);
    lv_obj_set_height(ui_Button7, 40);
    lv_obj_set_x(ui_Button7, -10);
    lv_obj_set_y(ui_Button7, 80);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText7 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_ButtonText7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText7, "7");

    ui_Button8 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button8, 65);
    lv_obj_set_height(ui_Button8, 40);
    lv_obj_set_x(ui_Button8, 60);
    lv_obj_set_y(ui_Button8, 80);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText8 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_ButtonText8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText8, "8");

    ui_Button9 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button9, 65);
    lv_obj_set_height(ui_Button9, 40);
    lv_obj_set_x(ui_Button9, 130);
    lv_obj_set_y(ui_Button9, 80);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText9 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_ButtonText9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText9, "9");

    ui_Button0 = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_Button0, 65);
    lv_obj_set_height(ui_Button0, 40);
    lv_obj_set_x(ui_Button0, 60);
    lv_obj_set_y(ui_Button0, 125);
    lv_obj_add_flag(ui_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonText0 = lv_label_create(ui_Button0);
    lv_obj_set_width(ui_ButtonText0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonText0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonText0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonText0, "0");

    ui_ButtonDot = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_ButtonDot, 65);
    lv_obj_set_height(ui_ButtonDot, 40);
    lv_obj_set_x(ui_ButtonDot, -10);
    lv_obj_set_y(ui_ButtonDot, 125);
    lv_obj_add_flag(ui_ButtonDot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTextDot = lv_label_create(ui_ButtonDot);
    lv_obj_set_width(ui_ButtonTextDot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonTextDot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonTextDot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonTextDot, ".");

    ui_ButtonDel = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_ButtonDel, 65);
    lv_obj_set_height(ui_ButtonDel, 40);
    lv_obj_set_x(ui_ButtonDel, 130);
    lv_obj_set_y(ui_ButtonDel, 125);
    lv_obj_add_flag(ui_ButtonDel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTextDel = lv_label_create(ui_ButtonDel);
    lv_obj_set_width(ui_ButtonTextDel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonTextDel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonTextDel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonTextDel, "Del");

    ui_ButtonDone = lv_button_create(ui_NumPad);
    lv_obj_set_width(ui_ButtonDone, 205);
    lv_obj_set_height(ui_ButtonDone, 30);
    lv_obj_set_x(ui_ButtonDone, -10);
    lv_obj_set_y(ui_ButtonDone, 170);
    lv_obj_add_flag(ui_ButtonDone, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonDone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonTextDone = lv_label_create(ui_ButtonDone);
    lv_obj_set_width(ui_ButtonTextDone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonTextDone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonTextDone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonTextDone, "Done");

    ui_GraphSettingsContainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_GraphSettingsContainer);
    lv_obj_set_width(ui_GraphSettingsContainer, 250);
    lv_obj_set_height(ui_GraphSettingsContainer, 60);
    lv_obj_set_align(ui_GraphSettingsContainer, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_GraphSettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlottingRateLabel = lv_label_create(ui_GraphSettingsContainer);
    lv_obj_set_width(ui_PlottingRateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlottingRateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlottingRateLabel, -40);
    lv_obj_set_y(ui_PlottingRateLabel, 15);
    lv_obj_set_align(ui_PlottingRateLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_PlottingRateLabel, "Plotting Rate (ms):");
    lv_obj_set_style_text_align(ui_PlottingRateLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlottingRateDropdown = lv_dropdown_create(ui_GraphSettingsContainer);
    lv_dropdown_set_options(ui_PlottingRateDropdown, "50\n100\n200\n500\n1000");
    lv_obj_set_width(ui_PlottingRateDropdown, 80);
    lv_obj_set_height(ui_PlottingRateDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlottingRateDropdown, 0);
    lv_obj_set_y(ui_PlottingRateDropdown, 5);
    lv_obj_set_align(ui_PlottingRateDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_PlottingRateDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_border_color(ui_PlottingRateDropdown, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PlottingRateDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PlottingRateDropdown, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_dropdown_set_selected(ui_PlottingRateDropdown, 1);
    lv_obj_add_state(ui_PlottingRateDropdown, LV_STATE_DISABLED);

    ui_StopPanel2 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_StopPanel2, 480);
    lv_obj_set_height(ui_StopPanel2, 30);
    lv_obj_set_x(ui_StopPanel2, 0);
    lv_obj_set_y(ui_StopPanel2, -25);
    lv_obj_set_align(ui_StopPanel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopPanel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_StopPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StopPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StopPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopText2 = lv_label_create(ui_StopPanel2);
    lv_obj_set_width(ui_StopText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopText2, "STOP BUTTON PRESSED!");
    lv_obj_set_style_text_color(ui_StopText2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopText2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    // Initialize variable adjustment slots
    variable_slots[0].slot_label = ui_Slot1Label;
    variable_slots[1].slot_label = ui_Slot2Label;
    variable_slots[2].slot_label = ui_Slot3Label;

    // Event callbacks for graph series checkboxes
    lv_obj_add_event_cb(ui_PlotLeftEncCheckbox, ui_event_PlotLeftEncCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotRightEncCheckbox, ui_event_PlotRightEncCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotArmEncCheckbox, ui_event_PlotArmEncCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotLeftDistanceCheckbox, ui_event_PlotLeftDistanceCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlotRightDistanceCheckbox, ui_event_PlotRightDistanceCheckbox, LV_EVENT_ALL, NULL);
    // Event callbacks for numpad buttons
    lv_obj_add_event_cb(ui_Button0,   NumpadButtonEvent, LV_EVENT_CLICKED, "0");
    lv_obj_add_event_cb(ui_Button1,   NumpadButtonEvent, LV_EVENT_CLICKED, "1");
    lv_obj_add_event_cb(ui_Button2,   NumpadButtonEvent, LV_EVENT_CLICKED, "2");
    lv_obj_add_event_cb(ui_Button3,   NumpadButtonEvent, LV_EVENT_CLICKED, "3");
    lv_obj_add_event_cb(ui_Button4,   NumpadButtonEvent, LV_EVENT_CLICKED, "4");
    lv_obj_add_event_cb(ui_Button5,   NumpadButtonEvent, LV_EVENT_CLICKED, "5");
    lv_obj_add_event_cb(ui_Button6,   NumpadButtonEvent, LV_EVENT_CLICKED, "6");
    lv_obj_add_event_cb(ui_Button7,   NumpadButtonEvent, LV_EVENT_CLICKED, "7");
    lv_obj_add_event_cb(ui_Button8,   NumpadButtonEvent, LV_EVENT_CLICKED, "8");
    lv_obj_add_event_cb(ui_Button9,   NumpadButtonEvent, LV_EVENT_CLICKED, "9");
    lv_obj_add_event_cb(ui_ButtonDot, NumpadButtonEvent, LV_EVENT_CLICKED, ".");
    lv_obj_add_event_cb(ui_ButtonDel, NumpadButtonEvent, LV_EVENT_CLICKED, "DEL");
    lv_obj_add_event_cb(ui_ButtonDone, ui_event_ButtonDone, LV_EVENT_ALL, NULL);
    //Event callback for dropdown
    lv_obj_add_event_cb(ui_PlottingRateDropdown, ui_event_PlottingRateDropdown, LV_EVENT_VALUE_CHANGED, NULL);
    //Event callbacks for adjust buttons
    lv_obj_add_event_cb(ui_Slot1Button, ui_event_Slot1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slot2Button, ui_event_Slot2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slot3Button, ui_event_Slot3Button, LV_EVENT_ALL, NULL);
    // Event callback for the back to main button
    lv_obj_add_event_cb(ui_BackToMainButton, ui_event_BackToMainButton, LV_EVENT_ALL, NULL);
}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

// NULL screen variables
    ui_SettingsScreen = NULL;
    ui_AdjustValuesLabel = NULL;
    ui_DisplaySeriesLabel = NULL;
    ui_CheckboxesContainer = NULL;
    ui_PlotLeftEncCheckbox = NULL;
    ui_PlotRightEncCheckbox = NULL;
    ui_PlotArmEncCheckbox = NULL;
    ui_PlotLeftDistanceCheckbox = NULL;
    ui_PlotRightDistanceCheckbox = NULL;
    ui_BackToMainButton = NULL;
    ui_GoBackLabel = NULL;
    ui_AdjustGainsContainer = NULL;
    ui_Slot1Label = NULL;
    ui_Slot2Label = NULL;
    ui_Slot3Label = NULL;
    ui_Slot1Button = NULL;
    ui_AdjustSlot1Label = NULL;
    ui_Slot2Button = NULL;
    ui_AdjustSlot2Label = NULL;
    ui_Slot3Button = NULL;
    ui_AdjustSlot3Label = NULL;
    ui_NumPad = NULL;
    ui_Button1 = NULL;
    ui_ButtonText1 = NULL;
    ui_Button2 = NULL;
    ui_ButtonText2 = NULL;
    ui_Button3 = NULL;
    ui_ButtonText3 = NULL;
    ui_Button4 = NULL;
    ui_ButtonText4 = NULL;
    ui_Button5 = NULL;
    ui_ButtonText5 = NULL;
    ui_Button6 = NULL;
    ui_ButtonText6 = NULL;
    ui_Button7 = NULL;
    ui_ButtonText7 = NULL;
    ui_Button8 = NULL;
    ui_ButtonText8 = NULL;
    ui_Button9 = NULL;
    ui_ButtonText9 = NULL;
    ui_Button0 = NULL;
    ui_ButtonText0 = NULL;
    ui_ButtonDot = NULL;
    ui_ButtonTextDot = NULL;
    ui_ButtonDel = NULL;
    ui_ButtonTextDel = NULL;
    ui_ButtonDone = NULL;
    ui_ButtonTextDone = NULL;
    ui_GraphSettingsContainer = NULL;
    ui_PlottingRateLabel = NULL;
    ui_PlottingRateDropdown = NULL;
    ui_StopPanel2 = NULL;
    ui_StopText2 = NULL;
}
