// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Custom GUI for VEX V5

#ifndef _CUSTOM_GUI_FOR_VEX_V5_UI_H
#define _CUSTOM_GUI_FOR_VEX_V5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "../src/Assets/screens/ui_Main_Menu.h"
#include "../src/Assets/screens/ui_Run_Program.h"
#include "../src/Assets/screens/ui_Select_Program.h"
#include "../src/Assets/screens/ui_Devices.h"
#include "../src/Assets/screens/ui_Settings.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2110221588);    // assets/UoA-Logo.png
LV_IMG_DECLARE(ui_img_937709628);    // assets/Distance-time_graph_example.png
LV_IMG_DECLARE(
    ui_img_play_arrow_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png);    // assets/play_arrow_60dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_pause_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png);    // assets/pause_60dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_stop_60dp_1f1f1f_fill0_wght400_grad0_opsz48_png);    // assets/stop_60dp_1F1F1F_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_keyboard_arrow_left_30dp_1f1f1f_fill0_wght400_grad0_opsz24_png);    // assets/keyboard_arrow_left_30dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(ui_img_1440723307);    // assets/electric-motor_12597972.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

// UI Related Functions
void sensor_chart_task(void *param);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
