// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef _VEX_RUNTIME_UI_UI_H
#define _VEX_RUNTIME_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "../src/Assets/screens/ui_MainScreen.h"
#include "../src/Assets/screens/ui_SettingsScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_settings_45dp_ffffff_fill0_wght400_grad0_opsz48_png);    // assets/settings_45dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
