// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#ifndef _VEX_RUNTIME_UI_UI_H
#define _VEX_RUNTIME_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "liblvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "../src/assets/screens/ui_MainScreen.h"
#include "../src/assets/screens/ui_SettingsScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_settings_45dp_ffffff_fill0_wght400_grad0_opsz48_png);    // assets/settings_45dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.png

// UI INIT
void ui_init(void);
void ui_destroy(void);
void init_plot_series(void);
void init_plot_slots(void);

extern lv_timer_t *graph_timer;
extern lv_timer_t *chart_resize_timer;
extern lv_timer_t *slider_labels_timer;
extern lv_timer_t *print_update_timer;
extern lv_timer_t *stop_button_timer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
