// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: VEX_Runtime_UI

#include "ui.h"
#include "ui_helpers.h"
#include "../include/liblvgl/lvgl.h"
#include "../include/main.h"
#include "Background_Functions.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

lv_timer_t *graph_timer = NULL;
lv_timer_t *chart_resize_timer = NULL;
lv_timer_t *slider_labels_timer = NULL;

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);

    //Custom initial actions
    ui_create_chart_series();
    graph_timer = lv_timer_create(graph_update_task, 50, NULL);
    chart_resize_timer = lv_timer_create(chart_update_task, 200, NULL);
    slider_labels_timer = lv_timer_create(update_gain_labels, 100, NULL);
}

void ui_destroy(void)
{
    ui_MainScreen_screen_destroy();
    ui_SettingsScreen_screen_destroy();
}
